### ISSUE TITLE
Subnets: integration with sBTC

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/stacks-sbtc#101]
FYI @obycode @saralab Issue to track integration with sBTC

https://github.com/hirosystems/stacks-subnets

**Comment by obycode** [comment]
Thanks @igorsyl. I believe a subnet should interact with sBTC the same as any other SIP-010 token, is that right? Anything else the subnet should be aware of?

**Comment by igorsyl** [comment]
I think so, but "unknown unknowns."

**Comment by obycode** [comment]
Need to define a simple subnet version of the sBTC contract to allow transfer, deposit, and withdrawal.
