### ISSUE TITLE
Research Peg-Out Priority Preference

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/stacks-sbtc#111]
introduce a mechanism whereby on peg-in, a user could indicate their peg-out priority preference. They could indicate something like a minimum collateralization ratio (CR). Those that have specified a lower mimimum CR would have their peg-outs processed first. Of course we’d need a way to incentivize those that indicate a lower liquidity preference as they are essentially performing the service of giving longer term stability to the peg.

Having a mechanism like this can give the market more information about the ‘depth’ of the peg. For instance I may be more comfortable pegging-in if I know I can set a high preference for pegging-out and am able to peg-out before others should the CR get too low for my liking.

I haven’t completely thought through how exactly this would be implemented, but thought it could be an interesting mechanism which could help reduce uncertainty around the peg and give it more stability and just wanted to get the idea out there.

https://forum.stacks.org/t/making-sbtc-ready-for-defi-prime-time/14421/20

**Comment by igorsyl** [comment]
Research funding approved: https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/845 cc @tycho1212

**Comment by radicleart** [comment]
Reserve a byte in the pegin request to indicate priority. Save it in sbtc contract to be redeemed on peg out?

Byte 3 priority
Bytes 4-12 amount 
Rest contract or account principal.

Problems.. user sends multiple pegin/out for same address?
