### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/stacks-sbtc#126]
```[tasklist]
### Tasks
- [ ] Create outline of docs
```

**Comment by igorsyl** [comment]
I can assign you @kenrogers once you accept the invite to collaborate on the core-eng repo.

**Comment by empeje** [comment]
Adding this nice docs that has been shared by @kenrogers in the meeting here.

> [sBTC and Nakamoto Documentation Outline][OUTLINE]

[OUTLINE]: https://stacksfoundation.notion.site/sBTC-and-Nakamoto-Documentation-Outline-17f7a7d44c644e8abe7b29c1442123f2
