### ISSUE TITLE
Hiro integration with sBTC

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/stacks-sbtc#137]
Sarala says order:

- Clarinet
  - https://github.com/Trust-Machines/core-eng/issues/98
- Stacks-blockchain API
  - https://github.com/Trust-Machines/core-eng/issues/102
- Stacks.js
  - https://github.com/Trust-Machines/core-eng/issues/97
  - https://github.com/Trust-Machines/core-eng/issues/99
  - https://github.com/Trust-Machines/core-eng/issues/101
- Explorer
  - https://github.com/Trust-Machines/core-eng/issues/100
- Wallet
  - https://github.com/Trust-Machines/core-eng/issues/94

TODO: Igor add other children issues

cc @saralab

**Comment by empeje** [comment]
For this integration I think it should be explain further to what each items mentioned above will do, how much is the integration and what is the scope for each items. Do we have a design draft/plan for this? If it's not available, perhaps a shared google docs can do the job to crowddesign the plan, wdyt?

**Comment by igorsyl** [comment]
Agreed. It's half-done. I created the ticket to remember. There are issues already for each item. I need to inlcude them here.

**Comment by empeje** [comment]
> TODO: Igor add other children issues

I take the liberty to link children issue to help me better understand the project.
