### ISSUE TITLE
Require contributors to sign off commits

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/stacks-sbtc#139]
We want to ensure contributors to our repo have the right to submit their code. A lightweight way to achieve this is to require contributors to sign off commits, and agree to a Developer Certificate of Origin [https://developercertificate.org/].

## Definition of done
- We have a CONTRIBUTORS.md file stating that signed off commits agree to the [DCO](https://developercertificate.org/).
- Our CI fails on commits that do not conform to this.

**Comment by igorsyl** [comment]
@netrome this needs to land

**Comment by netrome** [comment]
Why is this required? Is it due to our GPL licensed code?

**Comment by igorsyl** [comment]
@netrome ye. stacks signer and coord will become part of stacks-blockchain ecosystem. Same with bridge-web and bridge-api

**Comment by netrome** [comment]
Alright, so any contributor to stacks signer and coordinator will have to sign the Stacks CLA?

**Comment by igorsyl** [comment]
> If I could do it over, I would probably suggest looking into commit sign-offs instead:

Thank you @diwakergupta for saving us time!
cc @netrome need to do this.

**Comment by netrome** [comment]
We're moving our development to the Stacks Foundation for sBTC and therefore inheriting their routines and requirements for developers.
