### ISSUE TITLE
Mini sBTC Epic

### ISSUE THREAD

**Issue by empeje** [Trust-Machines/stacks-sbtc#150]
# Summary

Based on the [Mini sBTC paper][MINI_SBTC_PAPER] , I'm trying to breakdown the Mini sBTC project(s) using mindmap in order to build out the Mini sBTC "epic" that is well refined and scoped-out.

```mermaid
mindmap
  root((Mini sBTC))
    Projects
      2 Step Escrow Transaction Support Library #151
      Bitcoin Transaction Library #152
      Controller Contract #153
      Disbursement Clarity API #154
      Peg Web application sBTC Bridge
      Peg In Clarity API
      Peg Out Smart Contract for Request & Fullfilment #157
      Peg out Fulfillment sBTC Signer API #160
      Peg transfers #161
      sORD API #162
    Agents
      Stackers
        participate in sbtc
      Users
        participate in pegin pegout
      Observers
        querying chainstate
      Vigilantes
        updating sbtc state
```

At least there are 10 projects in this epic which includes but not limited to

1. https://github.com/Trust-Machines/core-eng/issues/151
2. https://github.com/Trust-Machines/core-eng/issues/152
3. https://github.com/Trust-Machines/core-eng/issues/153
4. https://github.com/Trust-Machines/core-eng/issues/154
5. https://github.com/Trust-Machines/core-eng/issues/155
6. https://github.com/Trust-Machines/core-eng/issues/156
7. https://github.com/Trust-Machines/core-eng/issues/157
10. https://github.com/Trust-Machines/core-eng/issues/160
11. https://github.com/Trust-Machines/core-eng/issues/161
12. https://github.com/Trust-Machines/core-eng/issues/162

## Proposal

1. I think to have well refined projects we need to extract each project into smaller epic (call it releases) and have tasks expanded in order to achieve user story for each project. (I can help build the issues with @igorsyl permission's) - **Output:** the epic will be a **github issue** where the description is the user stories.
2. Additionally I'd propose for an ad-hoc meeting for people interested in each project such that we can translate the user stories into a meaningful task that can have definition of done. We can be tactical with the tasks depending on the urgency and the implementation strategy. - **Output**: will be multiple tasks linked to each releases ticket, each task will have clear definition of done. The ad-hoc meeting can be an async discussion as well if time doesn't permit us.
3. Potentially we can weight each tasks as well using a simple labelling system a la story points using github label e.g. a 3 story points / weights can be labelled "3-points".

## Additional notes

I'm using Mermaid to mind map what's needs to be done where the code can be seen in this [gists][MIND_MAP]. Or can be seen live in [mermaid live][MIND_MAP_LIVE].

[MINI_SBTC_PAPER]: https://docs.google.com/document/d/1R33gZupJg0KsY-vRZYbVFwTHRmq2BCIvyPIVeY0JyGM/edit#
[MIND_MAP]: https://gist.github.com/jo-tm/89e1196c33cf38771fd52ba416788d9e
[MIND_MAP_LIVE]:  https://mermaid.live/edit?gist=https://gist.github.com/empeje/a52010b3200fd4238f6f1dfdcd708bc6

**Comment by igorsyl** [comment]
Wow. Amazing. Feel free to create issues. Please tag them with a new "sbtc-mini" tag so I can quickly review them.
Sent you an invite for tomorrows sBTC War Room.

**Comment by empeje** [comment]
I have added the child issues and link it to this issue. Feel free to review :smile: 


Additional, I'll join the War Room after my day job.
