### ISSUE TITLE
Support reclaiming commit transactions

### ISSUE THREAD

**Issue by empeje** [Trust-Machines/stacks-sbtc#151]
The commit-reveal protocol does not guarantee that a commit transaction is ever revealed. Therefore, users must be able to reclaim their funds from a commit transaction. The protocol strongly encourages including reclaim spend paths but does not specify how to do so. We should ensure the reference implementation of commit-reveal supports a reclaim path.

## Definition of done
The reference implementation of the commit-reveal protocol supports a user-friendly reclaim mechanism for committed funds.

**Comment by jo-tm** [comment]
@FriendsFerdinand can you scope this?

**Comment by jo-tm** [comment]
not in clarity WG , find the appropriate WG.

**Comment by jo-tm** [comment]
@netrome can you help me move this issue to appropriate WG?

**Comment by netrome** [comment]
Yep, this is essentially the reclaim path in the commit-reveal working group. I'll take care of it.

Tracking it in P-03 now. https://github.com/Trust-Machines/core-eng/issues/230
