### ISSUE TITLE
Bitcoin Transaction Library

### ISSUE THREAD

**Issue by empeje** [Trust-Machines/stacks-sbtc#152]
## Background

Taking directly from the paper

> This is the project encompassing the work required to authenticate, decode, and validate Bitcoin transactions in Clarity.  It must support the following user stories:
>  - As a library user, I can determine if a Bitcoin transaction was mined in a Bitcoin block, given the Bitcoin block header and a Merkle proof
> - As a library user, I can decode the first N inputs and outputs of a Bitcoin transaction (for some library constant N).
> - As a library user, I can decode the first N inputs’ witness scripts, as long as they are each less than W items long (for some library constants N and W).
> This library will be needed by each Clarity API.

Friedger has already built a library to interpret and verify whether Bitcoin transactions have been mined. The library was updated to make use of Clarity 2.1 features but does not currently support SegWit transactions.

## Definition
A stateless clarity-bitcoin library that can verify whether a SegWit transaction was mined and can also extract witness data and UTXOs.

## Motivation
Taproot transactions use SegWit so supporting SegWit transactions is crucial. Since we use a “commit-reveal” mechanism that encodes important information inside the witness data, we also need to be able to extract that data.

## Technical Risk
There are two main factor that can cause a delay:
Building this library requires a good understanding of the Bitcoin SegWit transaction format, which might require extra study.
Likewise, parsing Bitcoin transactions in Clarity is challenging work so limitations in the language itself can slow down the project.

## Dependencies
None

## Rough implementation plan & timeline
1. Segwit Transaction Parsing (Done)
2. Segwit Merkle Root Verification

Workload estimate is 5 days (2 already used)

**Comment by jo-tm** [comment]
Should be revoled with the other SegWit issue.

**Comment by jo-tm** [comment]
linked to https://github.com/Trust-Machines/stacks-sbtc/issues/253
