### ISSUE TITLE
Peg-In Clarity Smart Contract & API

### ISSUE THREAD

**Issue by empeje** [Trust-Machines/stacks-sbtc#156]
## Background

Taking directly from the paper

> This is the project encompassing the work required to enable `sbtc` to process a peg-in.  It must satisfy the following user stories:
> - As a vigilante, I can post the Stacker-signed peg-in transaction to `.sbtc` to materialize the user’s sBTC if the peg is in a good state.
> - As a vigilante, I can be denied the ability to post a peg-in transaction if the peg is in a bad state.

Peg-In happens on Bitcoin first, in that a user submits Bitcoin to a P2TR address and funds it with Bitcoin. Stackers then need to spend that Bitcoin within a specific timeframe and move it to the peg wallet address. Once that is done, the spend transaction is submitted to the sBTC protocol by anyone in order to mint the sBTC tokens to the user account that sent the peg-in.

## Definition
The peg-in smart contract can receive a Bitcoin peg-in transaction, it will then:
Verify the transaction is well-formed. It should contain the destination public key of the user.
confirm that it was mined and the minimum number of confirmations has been reached.
Trigger a mint of sBTC tokens to the user..

## Motivation
The peg-in smart contract is needed to mint sBTC in a trust-minised manner.

Technical Risk
The contract cannot work without the ability to check if a SegWit transaction was mined. It also needs to be able to retrieve the principal from the witness data.

Dependencies
Clarity-bitcoin library with SegWit support.

Rough implementation plan & timeline
Which main sub-deliveries are part of this project? How can we track and measure the progress?
When do we expect this to be completed?

**Comment by jo-tm** [comment]
- Has logic there.
- Not unit tested yet.
- Depends on the final version of library & SegWit.

**Comment by jo-tm** [comment]
@MarvinJanssen can you please provide an update on this here?

**Comment by jo-tm** [comment]
same for Peg-In @netrome, can you please paste some Peg-in TXs examples serialized and *deserialized* too?

**Comment by MarvinJanssen** [comment]
Work is being done here: #319.

- Added a new annotation for the Clarity unit test generation to mine blocks `@mine-blocks-before`
- Added some first unit tests.

**Comment by netrome** [comment]
> same for Peg-In @netrome, can you please paste some Peg-in TXs examples serialized and _deserialized_ too?

I'd love to, but we don't have test vectors for peg-in just yet. @soju-drinker is working on it.

**Comment by jo-tm** [comment]
Marvin: advances on #319, merged Fernando branch with SegWit extension library.

**Comment by jo-tm** [comment]
Burnchain mocks feature will come soon.
Need official test vector cases, better organised.

**Comment by jo-tm** [comment]
- Fernando mocked mining of Bitcoin block headers, this is very helpful.

**Comment by MarvinJanssen** [comment]
Updates:
- Can simulate mining Bitcoin blocks/transactions in Clarinet via testnet controller now.
- First peg-in tests that check if the transaction was mined, extract peg information, and mint sBTC tokens.
- Will push changes once the unit tests are updated.

**Comment by jo-tm** [comment]
- Can be read to merge with cumbersome testing using ad-hoc Bitcoin headers.
- Blocker: will be ideal to have Bitcon headers generator from @radicleart if possible.

**Comment by jo-tm** [comment]
@MarvinJanssen please add any updates if necessary.

**Comment by jo-tm** [comment]
Reviewing https://github.com/Trust-Machines/core-eng/pull/319
@MarvinJanssen please plan for Date Completion to be 16th June or June or 30th June (or earlier), use the **Week** field. So we have 2-week Sprint Granularity for June and not 1 week that is too tight. Also, add an **Estimation of #Days** for @igorsyl Gantt if you want.

**Comment by jo-tm** [comment]
@FriendsFerdinand wants to add a review too.
