### ISSUE TITLE
[stacks-coordinator] Closed alpha testing

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#16]
DoD: The coordinator only allows a pre-determined set of BTC addresses to peg-in/peg-out

Depends on #15 

Time estimate: 1 day

**Comment by igorsyl** [comment]
@netrome should we use labels instead of "[Coordinator]" prefix?

**Comment by netrome** [comment]
> @netrome should we use labels instead of "[Coordinator]" prefix?

@igorsyl sounds good to me. Labels will scale better as the project grows. Let me know if you want me to remove the prefixes, otherwise I see no harm in keeping them for the initial issues.

**Comment by igorsyl** [comment]
> > @netrome should we use labels instead of "[Coordinator]" prefix?
> 
> @igorsyl sounds good to me. Labels will scale better as the project grows. Let me know if you want me to remove the prefixes, otherwise I see no harm in keeping them for the initial issues.

I think prefix works ok for now. Let's upgrade for sBTC beta.

**Comment by netrome** [comment]
We're not doing this since alpha is no longer targeting mainnet
