### ISSUE TITLE
Peg Transfer/Handoff Clarity Contract

### ISSUE THREAD

**Issue by empeje** [Trust-Machines/stacks-sbtc#161]
**Background**
Every successful stacker/signer pool is marked by the transfer of all pegged-BTC held in threshold-wallet (n - 1) to the newly-voted upon threshold-wallet in cycle (n); this happens during a 100-block window known as the transfer window (sandwiched between the “voting” & “penalty”) windows. Like the peg-out & peg-in processes defined above, this hand-off of all pegged BTC starts on the Bitcoin blockchain & consists of two steps.  

First, stackers/signers in (n -1) create a P2TR address that either allows the registered stackers/signers in (n) to consume it & transfer it to the new peg-wallet/threshold wallet within the remaining transfer block window (100 - X) or allows the stackers/signers in (n - 1) to reclaim.

Once the stackers / signers in (n) the taproot script to consume the BTC & transfer it to new threshold/peg wallet, anyone (stackers/signers or observers or vigilantes) can relay to sbtc-controller (or maybe sbtc-stacking-pool) that the new stackers are now in possession of the peg-wallet.

**Definition**
The current sbtc-mini pegged-supply of BTC is successfully transferred from the current group of stackers/signers to the next group of stackers/signers; specifically, that the BTC peg balance is transferred from threshold-wallet (n - 1) to the newly-voted upon threshold-wallet by stackers/signers in threshold-wallet (n).

The system is considered “done” if following feature set is satisfied:

1. Stackers/signers in cycle (n-1) can create & fund a taproot address & script with the entirety of the BTC currently pegged in the old (n -1) threshold wallet
2. Stackers/signers in cycle (n) can consume (using the script in step 1) & transfer the pegged BTC to the newly-voted threshold wallet
3. Anyone (either stacker/signer pool or observers) can relay a fulfillment transaction from step 2 that proves that the new pool of stackers/signers are now in control of the beg balance.

**Motivation**
Without implementing the continuous transfer of the peg-balance to a consistently-changing group of stacker/signer volunteers we’d have to rely on a single centralized entity or a semi-centralized federation of “accepted” signers.

**Comment by jo-tm** [comment]
No description, not scoped.

**Comment by jo-tm** [comment]
@netrome what is this? is this part of Clarity WG? thx.

**Comment by netrome** [comment]
@jo-tm I don't know. This could refer to the peg handoff functionality, in which case it is tracked by https://github.com/Trust-Machines/core-eng/issues/231.

Since the ticket does not have a definition, and the title suggests it may be a duplicate let's close this one.

**Comment by setzeus** [comment]
Re-adopting / opening to reflect the need for a Peg-Transfer.clar contract for sBTC-mini. 

The pool contract needs to interact with this contract to so signers in cycle N can prove that pegged BTC has been moved to threshold-wallet for cycle N+1.

**Comment by netrome** [comment]
@setzeus nice. Can you update the description of the issue so it provides more context than just "TBD"?

**Comment by netrome** [comment]
> @netrome copy, updated accordingly.

Looking great, thank you!

**Comment by jo-tm** [comment]
Question from @setzeus :
- How we verify the amount?

**Comment by jo-tm** [comment]
No updates.

**Comment by jo-tm** [comment]
No updates.

**Comment by setzeus** [comment]
In [here](https://github.com/Trust-Machines/core-eng/blob/sbtc-mini-staking-pool-and-peg-transfer/sbtc-mini/contracts/sbtc-peg-transfer.clar) I’ve implemented the most basic use-case where we:

1. Check BTC tx provided was mined
2. Check stacking-pool items
    1. In “transfer” window
    2. Not already transferred
3. Check all output pubKeys belong to previous pool threshold wallet
4. Check aggregate value transferred is greater than registered peg-balance 

While writing this, I talked to Marvin/Fernando/Friedger which led me to the following observations / open-questions:

1. Still not sure how this transaction will look like (1 input from previous?)
2. How/will the signers consolidate UTOXs?
3. Or is this done over many validations?
4. How do we know the right amount was transferred over?   

This last issue is particularly important I also come across this in sbtc-stacking-pool since we need to prove BTC rewards were disbursed)

**Comment by jo-tm** [comment]
- First comments from Marvin review.
- Working though unit tests.

**Comment by jo-tm** [comment]
- working through reviews left in PR.

**Comment by jo-tm** [comment]
- lots of progress.
- all comments taken care off.
- Q: for @MarvinJanssen and @FriendsFerdinand

**Comment by jo-tm** [comment]
- No more comments left.
- Focusing on unit testing.
- Conflicts to be solved.
