### ISSUE TITLE
sORD API

### ISSUE THREAD

**Issue by empeje** [Trust-Machines/stacks-sbtc#162]
Probably need to have the following

- As a user I want to be able to explore sORD in Stacks Explorer
- As a developer I want to be able to interact with sORD in Clarity

**Comment by jo-tm** [comment]
This is a stretch goal, nice to have.

**Comment by netrome** [comment]
> @netrome is this the Standard Stacks API?

I guess the Stacks API is a part of this, but I assume more pieces need to be figured out to deliver the two user stories described in this ticket. The first step as I see it is to define what we mean by sORD. So far I only know it is some sort of representation of ordinals on Stacks.

**Comment by jo-tm** [comment]
@empeje is sORD the *Ordinal Support in Stacks*?
