### ISSUE TITLE
Taproot Tweaked Key and Frost

### ISSUE THREAD

**Issue by donpdonp** [Trust-Machines/stacks-sbtc#193]
The peg-in transaction for sbtc creates a taproot output. A taproot output enables schnorr singatures (replacing ECSDA). A schnorr signature is necessary so that the peg-out transaction can be signed using frost, which generates schnorr signatures.

A taproot creates a new concept called the internal key that is tweaked or modified by a process involving the contents of the tapscript[1]. The peg-in tx builder tweaks the recipient's public key to build the peg-in transaction, and the spender tweaks the private key in a similar fashion to spend the peg-in UTXO.

BIP341[3] describes how to tweak a key. While the BIP implies it is always used, the current integration test [2] passes for the keyspend (no attached bitcoin script) case without tweaking.

It is an open question whether the frost process can support the tweak operation during distributed key generation (DKG) which would be necessary for time-lock and other features.

cc @xoloki @MarvinJanssen 

[1] The root of the merkle tree that divides the bitcoin script at decision-points.
[2] frost-test/src/frost-btc.rs
[3] https://en.bitcoin.it/wiki/BIP_0341

**Comment by netrome** [comment]
I wonder if that's not already guaranteed by FROST. I would be surprised if the distributed key generation we use would allow that sort of malleability of the resulting aggregate public key.

I assmue this problem is the one you're considering @MarvinJanssen: https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#cite_ref-23-0

> **Why should the output key always have a taproot commitment, even if there is no script path?** If the taproot output key is an aggregate of keys, there is the possibility for a malicious party to add a script path without being noticed by the other parties. This allows to bypass the multiparty policy and to steal the coin. MuSig key aggregation does not have this issue because it already causes the internal key to be randomized. The attack works as follows: Assume Alice and Mallory want to aggregate their keys into a taproot output key without a script path. In order to prevent key cancellation and related attacks they use [MSDL-pop](https://eprint.iacr.org/2018/483.pdf) instead of MuSig. The MSDL-pop protocol requires all parties to provide a proof of possession of their corresponding secret key and the aggregated key is just the sum of the individual keys. After Mallory receives Alice's key A, Mallory creates M = M0 + int(t)G where M0 is Mallory's original key and t allows a script path spend with internal key P = A + M0 and a script that only contains Mallory's key. Mallory sends a proof of possession of M to Alice and both parties compute output key Q = A + M = P + int(t)G. Alice will not be able to notice the script path, but Mallory can unilaterally spend any coin with output key Q.

@xoloki do you know if FROST would be susceptible to that type of vulnerability?

**Comment by MarvinJanssen** [comment]
@netrome you are right I might have mixed up the footnote you cite. Still, I wonder if it is better to tweak the key anyway when used by `OP_CHECKSIG`. I do not know enough about it to say for sure.

**Comment by netrome** [comment]
> @netrome you are right I might have mixed up the footnote you cite. Still, I wonder if it is better to tweak the key anyway when used by `OP_CHECKSIG`. I do not know enough about it to say for sure.

We're not using `OP_CHECKSIG`, since key spending is a first-class concept in taproot. If tweaking with FROST would have been trivial I'd agree because why not. However, it would require substantial work to a distributed tweak in the signing algorithm. This type of modification also comes with risks as we might introduce new vulnerabilities in the protocol. Therefore I'd like to investigate if there is any need for the tweak first.

**Comment by MarvinJanssen** [comment]
What do you mean? The escrow addresses' unlock script contains the threshold pub key ending with `OP_CHECKSIG`, right?

```
'[<sBTC PAYLOAD> OP_DROP <THRESHOLD PUBKEY> OP_CHECKSIG]' 
```

E.g.:

```
'[0x3c001a7321b74e2b6a7e949e6c4ad313035b166509501700 OP_DROP 0xf855ca43402fb99cde0e3e634b175642561ff584fe76d1686630d8fd2ea93b36 OP_CHECKSIG]' 
```

**Comment by netrome** [comment]
> What do you mean? The escrow addresses' unlock script contains the threshold pub key ending with `OP_CHECKSIG`, right?
> 
> ```
> '[<sBTC PAYLOAD> OP_DROP <THRESHOLD PUBKEY> OP_CHECKSIG]' 
> ```
> 
> E.g.:
> 
> ```
> '[0x3c001a7321b74e2b6a7e949e6c4ad313035b166509501700 OP_DROP 0xf855ca43402fb99cde0e3e634b175642561ff584fe76d1686630d8fd2ea93b36 OP_CHECKSIG]' 
> ```
> 
> Edit: can the tweak not just happen at the end? If it is hardcoded then all clients would arrive at the same tweaked key anyway. I guess the footnote still applies. If you don't tweak then you cannot prove (to outsiders) that the key does not contain a hidden script path that circumvents the FROST process.

That's true. Although, what you're mentioning here is about producing the reveal transaction in commit-reveal, which is a script path spend with `OP_CHECKSIG`. To spend this output, the revealer (which could be the signers) would reveal the script and a merkle path to the script. There is no need to do any additional tweaking here. In taproot, tweaking only makes sense for a direct key spend which does not reveal any scripts.

The output of the reveal transaction (if it is a deposit) would be BTC funds sent directly to the sBTC wallet, managed by the signers. The address of this wallet is the public key generated with FROST. Here there are no scripts, and the only way to spend these funds should be by aggregating signature shares provided by a large subset of the signers. The question here is if we need to apply the tap tweak for this address or not. I.e. should the address be the public key generated with FROST or should it be this public key plus the tap tweak?

**Comment by MarvinJanssen** [comment]
>The address of this wallet is the public key generated with FROST. Here there are no scripts, and the only way to spend these funds should be by aggregating signature shares provided by a large subset of the signers.

The point I was trying to make here is that it could be useful to prove to outsiders that there is no hidden script path for this key somehow. Again, I do not know enough to say if FROST guarantees this or if it is somehow possible (even just theoretically) for an actor to embed a secret script path during the DKG process. If it is, then it might not be enough to just say "just look the source code is here". Applying the tweak with an `OP_FALSE` script at the end makes it easy to prove.

I also mentioned the script because I do not know if an untweaked pub key impacts the behaviour of `OP_CHECKSIG`. (Just raising some questions.)

**Comment by netrome** [comment]
> The point I was trying to make here is that it could be useful to prove to outsiders that there is no hidden script path for this key somehow. Again, I do not know enough to say if FROST guarantees this or if it is somehow possible (even just theoretically) for an actor to embed a secret script path during the DKG process. If it is, then it might not be enough to just say "just look the source code is here". Applying the tweak with an `OP_FALSE` script at the end makes it easy to prove.
> 
> I also mentioned the script because I do not know if an untweaked pub key impacts the behaviour of `OP_CHECKSIG`. (Just raising some questions.)

Yeah I agree we should provide assurances that there is no hidden spend path. This goes for the whole FROST security analysis too. We need to be certain that a single signer cannot forge a signature or embed another spend path in the resulting address. I hope we can prove that FROST is not vulnerable to script spend path injection, but if that is not the case it is of course interesting to investigate if we can incorporate the tap tweak in the distributed signing algorithm.

**Comment by netrome** [comment]
@xoloki has implemented support for tweaked keys in the wsts repo. Closing this issue.
