### ISSUE TITLE
Chore: Switch base58 library to https://crates.io/crates/bs58

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#320]
## Context
Currently we use https://github.com/debris/base58 which has two problems:

1. The error type returned on failed conversions does not implement `Display` (and also not `std::error::Error` by extension).
2. The library does not have a license file bundled with the source code.

This library seems objectively better and is also more widely adopted: https://crates.io/crates/bs58

## Definition of done
We use https://crates.io/crates/bs58 instead of https://github.com/debris/base58 for base58 encoding/decoding

**Comment by aryzing** [comment]
Saw this issue was created from the [discussion on the outdated `base58` crate on #318](https://github.com/Trust-Machines/core-eng/pull/318#discussion_r1184681822). If I understood correctly, the first step would be to update https://github.com/Trust-Machines/p256k1 and swap out `base58` for `bs58`, which does use `Debug`gable errors. The second step would be to update `core-eng` with the new errors types. 

If so, would you mind I have a go at the first step?

**Comment by xoloki** [comment]
> Saw this issue was created from the [discussion on the outdated `base58` crate on #318](https://github.com/Trust-Machines/core-eng/pull/318#discussion_r1184681822). If I understood correctly, the first step would be to update https://github.com/Trust-Machines/p256k1 and swap out `base58` for `bs58`, which does use `Debug`gable errors. The second step would be to update `core-eng` with the new errors types.
> 
> If so, would you mind I have a go at the first step? I'm approaching this as a "good first issue" for exercising my Rust.

Yeah go for it

**Comment by netrome** [comment]
> Saw this issue was created from the [discussion on the outdated `base58` crate on #318](https://github.com/Trust-Machines/core-eng/pull/318#discussion_r1184681822). If I understood correctly, the first step would be to update https://github.com/Trust-Machines/p256k1 and swap out `base58` for `bs58`, which does use `Debug`gable errors. The second step would be to update `core-eng` with the new errors types.
> 
> If so, would you mind I have a go at the first step? I'm approaching this as a "good first issue" for exercising my Rust.

Sounds great. I'm saying the same as @xoloki, go for it! 🚀

**Comment by xoloki** [comment]
`p256k1` done @netrome , thanks @aryzing !
