### ISSUE TITLE
sBTC Bitcoin Peg-in and Peg-out Test Vectors

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#340]
**Background**

The sBTC protocol requires special sequences of bitcoin transactions. Apart from designing the protocol specification on paper, test vectors are needed to prove that the peg-in and peg-out processors work. The test vectors should capture use-cases as well as edge-cases.

**Definition**

Test vector Bitcoin transactions and scripts of the following kind.

Peg-in:

* PI1) A well-formed peg-in commit transaction.
* PI2) A well-formed peg-in reveal transaction. (Stackers consumed the P2TR address.)
* PI3) A well-formed peg-in reclaim transaction. (Peg-in requester reclaimed the Bitcoin after expiry.)
* PI4) A malformed peg-in reveal transaction. (Invalid Stacks principal payload.)

Peg-out request:

* POR1) A well-formed peg-out request transaction.
* POR2) A malformed peg-out request transaction. (Invalid unlock script structure.)
* POR3) A malformed peg-out request transaction. (Valid unlock script structure but does not match witness program.)
* POR4) A malformed peg-out request transaction. (Invalid Stacker account payload, bad signature.)

Peg-out fulfillment:

* POF1) A well-formed peg-out request fulfillment by Stackers. (Bitcoin paid out to users by Stackers.)
* POF2) A well-formed peg-out request fulfillment by someone else. (Bitcoin paid out by random address.)

**Motivation**

We need confirmed test vectors to test the sBTC Mini protocol and make sure that it is compatible with the sBTC protocol design.

**Technical Risk**

None.

**Dependencies**

Nothing

**Rough implementation plan & timeline**

1. Peg-Out Vector Cases: POR1, POR2, POR3.
2. Peg-In Vector Cases: PI1, PI2, PI3, PI4.
3. Peg-Out Fulfillment: POF1, POF2.

**Comment by netrome** [comment]
Hey! Is anyone working on this? I just started extending the test vectors in https://github.com/Trust-Machines/core-eng/tree/main/test-vectors to use commit-reveal.

I'll generate some initial vectors for peg-in and peg-out-request and paste here as a start, but to comply with the full DoD we need to await the proper commit-reveal implementation in https://github.com/Trust-Machines/core-eng/pull/339

**Comment by jo-tm** [comment]
@netrome I think we will use the same test vectors. Will keep you posted.

**Comment by netrome** [comment]
Perfect, I noticed I forgot to post the vectors from https://github.com/Trust-Machines/core-eng/pull/382 here

**Peg in OP_RETURN**
```
02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffffffff020000000000000000516a4c4e69643c061a010101010101010101010101010101010101010116736274632d72656365697665722d636f6e74726163740000000000000000000000000000000000000000000000000000000000003905000000000000225120040404040404040404040404040404040404040404040404040404040404040400000000
```

**Peg in OP_DROP**
```
020000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffffffff020000000000000000056a036964773905000000000000225120040404040404040404040404040404040404040404040404040404040404040402764c4e3c061a010101010101010101010101010101010101010116736274632d72656365697665722d636f6e747261637400000000000000000000000000000000000000000000000000000000000000007576a920040404040404040404040404040404040404040404040404040404040404040487ad613c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c00000000
```

**Peg out request OP_RETURN**
```
02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffff0000030000000000000000516a4c4e69643e00000000000005390135af51a3d143749a43da266fd986fbdd7b1a1c858669ae10ee63075d15febce208bde8a35eee0deba178e6c1ae73067da918cb437db04077084960b0d78719c0000015000000000000001976a914050505050505050505050505050505050505050587ad2a00000000000000225120040404040404040404040404040404040404040404040404040404040404040400000000
```

**Peg out request OP_DROP**
```
020000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffffffff030000000000000000056a0369647715000000000000001976a914050505050505050505050505050505050505050587ad2a00000000000000225120040404040404040404040404040404040404040404040404040404040404040402764c4e3e00000000000005390135af51a3d143749a43da266fd986fbdd7b1a1c858669ae10ee63075d15febce208bde8a35eee0deba178e6c1ae73067da918cb437db04077084960b0d78719c0000000007576a920040404040404040404040404040404040404040404040404040404040404040487ad613c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c00000000
```

**Peg handoff OP_RETURN**
```
02000000010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffff0000020000000000000000536a036964480800000000000000434400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000225120040404040404040404040404040404040404040404040404040404040404040400000000
```

**Comment by jo-tm** [comment]
@FriendsFerdinand we have these test vectors, do we need to update anything on the Clarity Bitcoin Library?

**Comment by FriendsFerdinand** [comment]
> @FriendsFerdinand we have these test vectors, do we need to update anything on the Clarity Bitcoin Library?

This doesn't change anything on the library.

**Comment by jo-tm** [comment]
@FriendsFerdinand gotcha
