### ISSUE TITLE
Add length-prefixing to contract names in peg-in requests

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#342]
Spawned from [this discord discussion](https://discord.com/channels/1076608263983997008/1105549945588690964/1106605070826619011).

## Context
It would be much easier to extract contract names from peg in ops in Clarity if the contract name strings were length-prefixed. I don't see any reason not to length-prefix them. We will loose one byte of contract name length but otherwise we should be fine. Let's try it out.

## Definition of done
The peg in requests contain a byte before the contract name stating the length of it. This is updated in:
1. The SIP (which currently does not even mention the contract)
2. The Stacks implementation
3. Any test vectors and test vector implementations

**Comment by netrome** [comment]
FYI @MarvinJanssen

**Comment by MarvinJanssen** [comment]
Further reference here: https://github.com/Trust-Machines/core-eng/pull/339#discussion_r1194208407

**Comment by netrome** [comment]
This has been added to the sBTC docs and will be included in the sBTC SDK
