### ISSUE TITLE
Introduce a version byte in all sBTC payloads

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#344]
For forward compatible parsing of sBTC data, we would like to introduce a version byte in all sBTC payloads. Currently all payloads lead with
```
|-------|---|-------------------------|
  magic  op  (op specific)
```

We want to change this to
```
|-------|---|---|-----------------------|
  magic  op  version (op specific)
```

## Definition of done
All sBTC payloads contain a sBTC version byte. This includes

1. Stacks wire formats
2. Any applicable test vectors
3. sBTC SIP (or at least a comment in the SIP) - this may be replaced with a master design doc

**Comment by netrome** [comment]
> This includes stacks payloads with no magic bytes cf op_drop data ?
Yes, including OP_DROP data.
 
> Is the initial value `1`, unsigned byte?
Not decidded. Spontaneously I'd start with version `0`.

**Comment by MarvinJanssen** [comment]
Thanks for posting @netrome!

Having a version byte in `OP_DROP` would be good to be on the safe side I think.

**Comment by netrome** [comment]
> Thanks for posting @netrome!
> 
> Having a version byte in `OP_DROP` would be good to be on the safe side I think.
> 
> Edit: Want to clarify it is just my initial thought to have a version byte. We should think of scenarios where/if it actually ever comes into play. Since the protocol goes through cycles, it is possible to coincide an upgrade with a cycle end because by then all BTC commits will be settled. On the Clarity side you can possibly get away with only having a guard based on the burn chain height.

Yeah I don't know any scenario where we would need this. In all places we store and parse these payloads we will know the assoicated burnchain height, which we could use to differentiate between format versions.

Let's hold this thought until we can come up with a concrete use case.

**Comment by netrome** [comment]
Given the lack of a scenario where this would be helpful I'm closing this ticket.
