### ISSUE TITLE
Review Deployment Config Clarinet for sbtc-mini

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#419]
Targetting sBTC Mini MVP.

**Comment by jo-tm** [comment]
Any caveats or risks that we may face deploying into Mainnet please add them here! cc/ @MarvinJanssen @setzeus @FriendsFerdinand

**Comment by MarvinJanssen** [comment]
Is @radicleart also evaluating this? (Devnet.)

Deployment config can follow the bootstrap code. In #512 it is abstracted into its own file `tests/bootstrap.ts`.

**Comment by jo-tm** [comment]
@radicleart working on a DevNet for sBTC (https://github.com/Stacks-Builders/sbtc-bridge-api/pull/47), related to this issue.
Mike issues he found are more related to PoX-4.

**Comment by jo-tm** [comment]
Mike says issues unrelated to Clarity code.

**Comment by jo-tm** [comment]
No updates, we need to continue discussion on bootstrapping.

**Comment by jo-tm** [comment]
Needs more specs on DevNet.
