### ISSUE TITLE
[stacks-signer] Storage solution for private keys generated

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#42]
The stacks-signer will generate private keys for each DKG round. These should be persisted in case the system restarts or if we need manual intervention.

DoD: The stacks-signer is able to persist private keys, and access these by round_id.

Open question: We don't want to loose old keys. Can we forbid overwriting existing values, or do we need to store all writes in an event log?

**Comment by igorsyl** [comment]
> The stacks-signer will generate private keys for each signing round.
I thought for frost v1 private keys are generated during dkg step only and not for signing steps.
@xoloki

**Comment by netrome** [comment]
> I thought for frost v1 private keys are generated during dkg step only and during the signing step.

Right, I meant DKG round. I'll update the description.

**Comment by xoloki** [comment]
> > The stacks-signer will generate private keys for each signing round.
> 
> I thought for frost v1 private keys are generated during dkg step only and during the signing step.
> 
> > Open question: We don't want to loose old keys. Can we forbid overwriting existing values, or do we need to store all writes in an event log?
> 
> We can use append-only sqlite. I know @xoloki likes lmdb but signer will eventually integrate into stacks-blockchain repo which uses sqlite.
> 
> cc @xoloki

I prefer key val storage in general, lmdb in Rust and leveldb in C++.   But SQLite is totally fine, as long as you're not storing a full Blockchain 😹

**Comment by igorsyl** [comment]
Agree with @xoloki on key val being the right db type for this case, however we need to weight this advantage vs the cost of supporting and integrating a new db lib in stacks-blockchain.

**Comment by netrome** [comment]
Agreed. I tend to use [sled](https://crates.io/crates/sled) for personal projects. I've been interested in trying out [persy](https://persy.rs/) as well.
