### ISSUE TITLE
`is-protocol-caller`: Any particular reason this function has a parameter?

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#436]
Random Q / not blocking merge but any particular reason this function has a parameter? 
Doesn't look like "who" is ever used?

_Originally posted by @setzeus in https://github.com/Trust-Machines/core-eng/pull/319#discussion_r1227991216_

**Comment by MarvinJanssen** [comment]
The last remaining contract (token contract) has been addressed in #513.

**Comment by jo-tm** [comment]
PR #513 will address this issue.
