### ISSUE TITLE
Improve the sbtc-cli to output JSON

### ISSUE THREAD

**Issue by stjepangolemac** [Trust-Machines/stacks-sbtc#444]
To improve compatibility with scripting tools commands should output JSON.

**Comment by igorsyl** [comment]
Rename to sbtc-cli to be consistent with blockstack-cli? Awesome tool, btw! Good example of what we need in `stacks-sbtc.js`. cc @saralab

**Comment by igorsyl** [comment]
cc @kenrogers to add to dev docs.
