### ISSUE TITLE
sBTC alpha burn calls are failing

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#445]
While testing alpha we now have the deposit flow working :tada: :rocket: 

However, all our burn transactions so far has been failing. Examples:

https://explorer.hiro.so/txid/0x79c7fd622ccf36b70c855374c0b90fd899c33d9581f088b54f1365d62eeca55c?chain=testnet
https://explorer.hiro.so/txid/0x847201b9aed7c7119f9061ee401ab24d6a9b474429efc1efb14f938eb39d5c13?chain=testnet
https://explorer.hiro.so/txid/0x847201b9aed7c7119f9061ee401ab24d6a9b474429efc1efb14f938eb39d5c13?chain=testnet

### How to reproduce
The simplest way is to explicitly create a burn transaction using the sBTC bridge app admin page https://testnet.stx.eco/admin?net=testnet

Alternatively, trigger a withdrawal flow to see the coordinator create a failing burn op

### Definition of done
We can generate burn transactions which don't fail

**Comment by netrome** [comment]
Updates:
Error code: u1. This code can mean `err-invalid-caller` in the sBTC contract but can also mean "(err u1) -- sender does not have enough balance to burn this amount or the amount specified is not positive" from the `ft-burn?` call. https://docs.stacks.co/docs/clarity/language-functions#ft-burn

One theory: The address did not have enough funds at any of the calls, let's try another call. We're skeptical, since we had previous sBTC at the time of the last two burn transactions.

Testing this theory: Here's a new burn tx (in mempool at the time of writing): https://explorer.hiro.so/txid/0xf27cf0b91a62f85fb9cfa080c25269e7e7998b4a29ec37803cd2b048c87f2b0a?chain=testnet

**Comment by netrome** [comment]
The new burn tx is in a microblock and was successful! https://explorer.hiro.so/txid/0xf27cf0b91a62f85fb9cfa080c25269e7e7998b4a29ec37803cd2b048c87f2b0a?chain=testnet

**Comment by netrome** [comment]
Another withdrawal in progress: https://mempool.space/testnet/tx/293822775d60182bee32cb24e18939cc17170e33a4ecb0789951bf448737decc

**Comment by stjepangolemac** [comment]
Just tried another withdrawal and saw this:
```
Jun 15 11:33:55 sbtc-large stacks-coordinator[317763]: 2023-06-15T11:33:55.112959Z  INFO stacks_coordinator::coordinator: Polling for withdrawal and deposit requests to process...
Jun 15 11:33:55 sbtc-large stacks-coordinator[317763]: 2023-06-15T11:33:55.114612Z  INFO stacks_coordinator::peg_queue::sqlite_peg_queue: Checking block heights 2437814 to 2437814
Jun 15 11:33:55 sbtc-large stacks-coordinator[317763]: 2023-06-15T11:33:55.352621Z  WARN stacks_coordinator::stacks_node::client: Failed to broadcast transaction to the stacks node: "ConflictingNonceInMempool"
Jun 15 11:33:55 sbtc-large stacks-coordinator[317763]: 2023-06-15T11:33:55.357663Z ERROR stacks_coordinator: An error occurred running the coordinator: Stacks Node Error: Broadcast failure: ConflictingNonceInMempool
Jun 15 11:33:55 sbtc-large systemd[1]: coordinator.service: Succeeded.
Jun 15 11:33:55 sbtc-large systemd[1]: coordinator.service: Scheduled restart job, restart counter is at 5.
Jun 15 11:33:55 sbtc-large systemd[1]: Stopped sBTC coordinator.
Jun 15 11:33:55 sbtc-large systemd[1]: Started sBTC coordinator.
Jun 15 11:33:55 sbtc-large stacks-coordinator[318284]: 2023-06-15T11:33:55.636518Z  INFO stacks_coordinator::coordinator: Initializing stacks coordinator...
Jun 15 11:33:55 sbtc-large stacks-coordinator[318284]: 2023-06-15T11:33:55.717620Z  INFO stacks_coordinator::bitcoin_node: Wallet already exists
Jun 15 11:33:55 sbtc-large stacks-coordinator[318284]: 2023-06-15T11:33:55.781026Z  INFO stacks_coordinator: Running Coordinator
Jun 15 11:33:55 sbtc-large stacks-coordinator[318284]: 2023-06-15T11:33:55.781065Z  INFO stacks_coordinator::coordinator: Polling for withdrawal and deposit requests to process...
```

**Comment by netrome** [comment]
I've spotted one error in our sBTC CLI for the withdrawals. I'm not sure if this causes the burn failure, but I'll fix it and try doing a deposit tx with the fix.

**Comment by netrome** [comment]
Trying another withdrawal with the CLI fix from https://github.com/Trust-Machines/stacks-sbtc/pull/470

https://mempool.space/testnet/tx/64556e823c0cc282ca23701d5bb325a525b3d5a4ecdee185c6671239bf8c0793

**Comment by netrome** [comment]
I've experienced some operational issues with our stacks node, which blocks further investigation of this in alpha https://github.com/Trust-Machines/stacks-sbtc/issues/471

**Comment by stjepangolemac** [comment]
Just tried to withdraw and coordinator crashed.

```
Jun 26 12:09:57 sbtc-large stacks-coordinator[474268]: 2023-06-26T12:09:57.412412Z  INFO stacks_coordinator::coordinator: Broadcasted withdrawal sBTC transaction: aadf9d7d5e46798f2253902a0dd12
76b8eb4db99bfa9e7c8dfc3f770e7af4dd7                                                                                                                                                             
Jun 26 12:09:57 sbtc-large stacks-coordinator[474268]: 2023-06-26T12:09:57.432894Z ERROR stacks_coordinator: An error occurred running the coordinator: Peg Wallet Error: Bitcoin Wallet Error: 
Fulfillment UTXO amount does not equal the fulfillment fee.                             
```

**Comment by jferrant** [comment]
Depends on https://github.com/stacks-network/stacks-blockchain/issues/3781

This requires that we fix the peg out request format to include a source address as we cannot use the BTC private key used to sign the transaction to generate the stx address.

**Comment by netrome** [comment]
Since burns are successfull, I'll close this one.
