### ISSUE TITLE
Track the vout index of the Peg-In commitment Transaction

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#462]
I guess to do it right we need to track the vout index of the peg-in commitment transaction.

Edit: to be more explicit, currently we don't send the peg-in commit transaction to the protocol. There was an assumption that the signers build specific transactions so perhaps we can get away with just taking the index from the vin.

_Originally posted by @MarvinJanssen in https://github.com/Trust-Machines/core-eng/pull/319#discussion_r1233065717_

**Comment by MarvinJanssen** [comment]
Addressed in #514.
