### ISSUE TITLE
Implement Stacking Pool Delegate Registration for sBTC Signers with Lifecycle Updates (POX4)

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#465]
## AKA Merge sBTC-Mini Stacking/Signing Lifecycle Updates (POX4)

As an sBTC peg maintainer, I want the POX4 sBTC-Mini stacking/signing lifecycle updates merged so that I have an updated process for voting, registering, and maintaining the sBTC peg under the new POX4 protocol.

### Registration

- Need to collapse the existing sbtc-mini logic of a two-step pre-registration & registration process into (likely) a single POX-4 registration function
- Signer/Stacker can pre-register to register (may kill)
- Signer/Stacker can register to vote & sign"

**Comment by jo-tm** [comment]
@setzeus blocked by annotations. Issue to be opened: Bootstrapping problem, who will be the first group of signers to pre-register?

**Comment by jo-tm** [comment]
@setzeus @igorsyl if this features is not for "standalone" contracts Mini without changes to PoX consensus, can we move to a future milestone?

**Comment by setzeus** [comment]
On the Stacks 3.0 roadmap we've split features into standalone contracts (released in v1 - v3 of mini) _& then_ a feature titled "Integration of sBTC into POX-4 contract" that doesn't have a deliverable until MVP In Production (est. October). 

So I think the appropriate title for this issue should be instead (& remain in this milestone):

"Mini-v1: Registration"

If there are no objections I'll update title in <36 hours.

**Comment by MarvinJanssen** [comment]
@setzeus the main blocker was a limit in the test generation script. Changing it so it is functional for testing across multiple calls with mining blocks in between and more. The new unit test generation script parses the entire contract. Tests are no longer limited to one contract function.

**Comment by jo-tm** [comment]
@setzeus : working on test annotations for mining empty blocks to push the chain ahead an being in another window, blocker #519

**Comment by jo-tm** [comment]
in progress, changes happening in #578
