### ISSUE TITLE
CI hiccup: test (macos-latest) is broken

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#466]
The `macos-latest` tests are failing in CI, but this is not reproducible locally.

Example errors:
https://github.com/Trust-Machines/core-eng/actions/runs/5294893814/jobs/9593253073?pr=459
https://github.com/Trust-Machines/core-eng/actions/runs/5313903835/jobs/9634089890#step:11:1348

Error message:
```
Error: Invalid port specified in -bind: '0.0.0.0:0'
test frost_btc has been running for over 60 seconds
test frost_btc ... FAILED
```

### Mitigation plan:
1. Disable the macos-latest target: https://github.com/Trust-Machines/core-eng/pull/467
2. Fix the problem
3. Re-enable the target

### Definition of done
The CI bug is fixed

**Comment by AshtonStephens** [comment]
I'm taking this over - it's a good ticket to get familiar with the testing practices of this repo. Hoping to have a good solution by Friday.

**Comment by AshtonStephens** [comment]
This port is specified in [test-utils/src/lib.rs#L114](https://github.com/Trust-Machines/stacks-sbtc/blob/e2b21b4cbca1380fb573d5a02c5da99c8f74bc13/test-utils/src/lib.rs#L114) which is almost certainly not right, but is for some reason working with all the other environments. The odder thing is that when I change the port to something more correct based on the [min and max port](https://github.com/Trust-Machines/stacks-sbtc/blob/e2b21b4cbca1380fb573d5a02c5da99c8f74bc13/test-utils/src/lib.rs#L40-L41), like `20001` I get this error: 

```
 Error: Unable to bind to 0.0.0.0:20001 on this computer. Bitcoin Core is probably already running.
 Error: Failed to listen on any port. Use -listen=0 if you want this.
```

Looking into what might be the issue.

**Comment by CharlieC3** [comment]
You may already know this but a quick look through suggests macos/darwin does not map port 0 to mean any port, so it's being interpreted literally. On other OS's, it seems this is a shortcut to let the OS pick a random port not being used at the moment, thus avoiding any conflicts.
For this to work on macos, I'm guessing you'll either need to figure out if macos has another way of telling it to use any port aside from specifying port 0. Alternatively, you can rework the test logic to find an empty port on the current machine and use that.
