### ISSUE TITLE
Stacks node keeps getting stuck in sBTC alpha VM

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#471]
The stacks node we are running is from this branch: https://github.com/Trust-Machines/stacks-blockchain/tree/2023-05-30-383-next-master-merge

We have experienced several times now that it stopped syncing new Stacks blocks. To remedy this we have restarted the node from the latest hiro snapshot: https://archive.hiro.so/testnet/stacks-blockchain/

However, only today I had to restart it twice from different snapshots. In both cases, the node processes a few stacks blocks and advances the chain tip only to get stuck and never advance again.

### Definition of done
We understand what's causing the node to get stuck, and have a plan to mitigate the issue.

**Comment by netrome** [comment]
Restarted from the same snapshot, and it's again getting stuck at 109187 (~40 blocks after the snapshot begun). I'll dig deeper in the logs and try to figure out what's going on here.

**Comment by netrome** [comment]
There's a lot of {"error": "transaction rejected" ...} logs from what seems to be the time the node is freezing. An interesting example is this one:
```
Jun 21 13:32:29 sbtc-large stacks-node[384577]: WARN [1687354349.195097] [src/net/p2p.rs:5254] [relayer-http://0.0.0.0:20443] Transaction rejected from mempool, {"error":"transaction rejected","reason":"TooMuchChaining","reason_data":{"actual":114,"expected":99,"is_origin":true,"message":"Nonce would exceed chaining limit in mempool","principal":"ST341674G6TJ28SMD8NAE8QGVEC4KDNNX7QGV2W1Z"},"txid":"1db602666a909bcb9e699dc0565681677d6b3fc0b5146e6e70cbd717250b9ee1"}
```

Since the transaction seems to have gone through in https://explorer.hiro.so/txid/0x1db602666a909bcb9e699dc0565681677d6b3fc0b5146e6e70cbd717250b9ee1?chain=testnet

**Comment by netrome** [comment]
> > Restarted from the same snapshot, and it's again getting stuck at 109187 (~40 blocks after the snapshot begun). I'll dig deeper in the logs and try to figure out what's going on here.
> 
> Suggestions:
> 
>     * Try cross-posting this issue to stacks-network GitHub org if you need help.
> 
>     * Thread dump the stacks-node process to find any deadlocks or I/O blocking calls.

Right I can clarify. The node keeps running, but it never updates the stacks chain tip. I'll update the description. We've experienced the same symptoms before, when it was caused by a hard fork. However no hard fork has happened since. The other suggestions we got at the time was to try restarting the node:

https://discord.com/channels/621759717756370964/730814571517968436/1113087247001075722

**Comment by netrome** [comment]
I'm experimenting now with swapping the node to one running on the latest master to see if it suffers from the same problem. However, I realize how easy it is to just do `cargo build --release` and forget to add `-p stacks-node`. It is possible that we were running the pre-2.4 hard fork stacks node. That would then explain this behavior.

**Comment by netrome** [comment]
> I'm experimenting now with swapping the node to one running on the latest master to see if it suffers from the same problem. However, I realize how easy it is to just do `cargo build --release` and forget to add `-p stacks-node`. It is possible that we were running the pre-2.4 hard fork stacks node. That would then explain this behavior.

Nope, we were running our merge after 2.4. I tried running a Stacks node on latest master and it catches up. Next experiment is to see if the problem arises when running directly against the 2.4 tag (on a93c2867df7bea946fcd99994bf73dbd54d6d0d3 which our next-master-merge was based on)

**Comment by netrome** [comment]
The node on a93c2867df7bea946fcd99994bf73dbd54d6d0d3 also catches up. We can conclude that the bug is caused by some of the changes merged in our `2023-05-30-383-next-master-merge` branch. I'll look into it deeper and inspect the logs to figure out what the issue may be.

**Comment by netrome** [comment]
I have looked into the logs, comparing the latest successful run from the last time we got stuck. There is a lot of noise in these logs, but these lines stand out to me as potential interesting leads. These log lines are only present in the failing run, and I'm not finding anything similar in the successful one:

```
Jun 21 13:29:35 sbtc-large stacks-node[384577]: INFO [1687354175.463475] [src/net/download.rs:528] [p2p-(0.0.0.0:20444,0.0.0.0:20443)] Remote neighbor facade09+80000000://35.199.30.38:20444 (UrlString("http://35.199.30.38:20443")) does not actually have block 438470 indexed at b847ac32be5e400ad50cc561bcf10789cc36903944a3706d4091d4f2bb89773e (84c3da9ddd22df1779fcb4eb8479e9a71575db34)
Jun 21 13:29:38 sbtc-large stacks-node[384577]: WARN [1687354178.140928] [src/chainstate/stacks/db/blocks.rs:1712] [relayer-http://0.0.0.0:20443] Discontinuous microblock stream: expected seq 4, got 5
Jun 21 13:29:38 sbtc-large stacks-node[384577]: WARN [1687354178.222377] [src/chainstate/stacks/db/transactions.rs:414] [relayer-http://0.0.0.0:20443] Bad nonce: origin account ST1THPCZ9BDQW3JMHSRVFKXNMR1R6DBRZHKRSRYX0 nonce of tx 0fd26b8d5de977638f95b1c9719ce9c39fc3af83c6b365456d9e5a4863345473 is 0 (expected 3)
Jun 21 13:29:38 sbtc-large stacks-node[384577]: WARN [1687354178.222469] [src/chainstate/stacks/db/unconfirmed.rs:316] [relayer-http://0.0.0.0:20443] Encountered invalid stacks microblock: Bad nonce: origin account ST1THPCZ9BDQW3JMHSRVFKXNMR1R6DBRZHKRSRYX0 nonce of tx 0fd26b8d5de977638f95b1c9719ce9c39fc3af83c6b365456d9e5a4863345473 is 0 (expected 3)
```

**Comment by netrome** [comment]
I've uploaded the full logs here: https://drive.google.com/drive/u/0/folders/1RnCggSxSC3jRIbW5ZY_wzv0UxhBxNShH

**Comment by stjepangolemac** [comment]
Stacks node was running without issues for a couple of hours. It stopped syncing when it encountered a BTC block with an sBTC operation. It's stil lreceiving burnchain blocks but unfortunately stacks tip is not advancing.

**Comment by diwakergupta** [comment]
@stjepangolemac have you run the node with DEBUG logs enabled? I looked through the logs @netrome uploaded but no debug logs in there. If you want to debug, you'll want to have debug logs :)

@jcnelson's suggestion on Discord is a good place to start: "Have you verified whether or not the consensus hash for the first sBTC burnchain block is the same as an unaltered node? Because if it isn't, then no subsequent stacks blocks will be valid (i.e. the sBTC burnchain transactions caused a hard fork because the sBTC node processed them as first-class burnchain ops, whereas unaltered nodes did not)"

@netrome w.r.t the log lines you posted, the invalid blocks message is definitely suspect. Though in general account specific issues (e.g. bad nonce or insufficient balance) are benign and not indicative of any underlying issues with the node itself.

You can find some more logging tips here: https://github.com/stacks-network/stacks-blockchain/wiki/All-About-Logs

**Comment by stjepangolemac** [comment]
@diwakergupta I've just checked and the hash indeed seems to be different. Maybe I'm not comparing the right values, here's what I see:

<details>
<summary>/v2/info</summary>
```json
{
  "peer_version": 4207599113,
  "pox_consensus": "1c7d466803eb6013d78d85b6192a6cfe5f6becb7",
  "burn_block_height": 2439342,
  "stable_pox_consensus": "deeb23f68fb8ec986a3c4374eefe70a540dfbcbd",
  "stable_burn_block_height": 2439335,
  "server_version": "stacks-node 0.0.1 (HEAD:3b43af677+, release build, linux [x86_64])",
  "network_id": 2147483648,
  "parent_network_id": 118034699,
  "stacks_tip_height": 109848,
  "stacks_tip": "e4c25dce67717dd0e6b6e5366ccfc0f541e3e48471c3dfb013bdb59f85e92004",
  "stacks_tip_consensus_hash": "2384841d004f9e4693f9ade6c9a4b5fc838f0471",
  "genesis_chainstate_hash": "74237aa39aa50a83de11a4f53e9d3bb7d43461d1de9873f402e5453ae60bc59b",
  "unanchored_tip": null,
  "unanchored_seq": null,
  "exit_at_block_height": null,
  "node_public_key": "02092177339077565b2a57b03baa7d5aa9ac5cbf4038c0cc74b73b6b181db99e5b",
  "node_public_key_hash": "f627afd3df97dc92ecae26119ccd977fcf693aef",
  "affirmations": {
    "heaviest": "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnppnnnnnnnnnnnnnnnnnnnnnnnnpppppnnnnnnnnnnnnnnnnnnnnnnnpppppppppppppppnnnnnnnnnnnnnnnnnnnnnnnppppppppppnnnnnnnnnnnnnnnnnnnppppnnnnnnnnnnnnnnnnnnnnnnnppppppppnnnnnnnnnnnnnnnnnnnnnnnppnppnnnnnnnnnnnnnnnnnnnnnnnppppnnnnnnnnnnnnnnnnnnnnnnnnnppppppnnnnnnnnnnnnnnnnnnnnnnnnnppnnnnnnnnnnnnnnnnnnnnnnnnnpppppppnnnnnnnnnnnnnnnnnnnnnnnnnnpnnnnnnnnnnnnnnnnnnnnnnnnnpppnppppppppppppppnnppppnpaaa",
    "stacks_tip": "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnppnnnnnnnnnnnnnnnnnnnnnnnnpppppnnnnnnnnnnnnnnnnnnnnnnnpppppppppppppppnnnnnnnnnnnnnnnnnnnnnnnppppppppppnnnnnnnnnnnnnnnnnnnppppnnnnnnnnnnnnnnnnnnnnnnnppppppppnnnnnnnnnnnnnnnnnnnnnnnppnppnnnnnnnnnnnnnnnnnnnnnnnppppnnnnnnnnnnnnnnnnnnnnnnnnnppppppnnnnnnnnnnnnnnnnnnnnnnnnnppnnnnnnnnnnnnnnnnnnnnnnnnnpppppppnnnnnnnnnnnnnnnnnnnnnnnnnnpnnnnnnnnnnnnnnnnnnnnnnnnnpppnppppppppppppppnnppppnpaaaappp",
    "sortition_tip": "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnppnnnnnnnnnnnnnnnnnnnnnnnnpppppnnnnnnnnnnnnnnnnnnnnnnnpppppppppppppppnnnnnnnnnnnnnnnnnnnnnnnppppppppppnnnnnnnnnnnnnnnnnnnppppnnnnnnnnnnnnnnnnnnnnnnnppppppppnnnnnnnnnnnnnnnnnnnnnnnppnppnnnnnnnnnnnnnnnnnnnnnnnppppnnnnnnnnnnnnnnnnnnnnnnnnnppppppnnnnnnnnnnnnnnnnnnnnnnnnnppnnnnnnnnnnnnnnnnnnnnnnnnnpppppppnnnnnnnnnnnnnnnnnnnnnnnnnnpnnnnnnnnnnnnnnnnnnnnnnnnnpppnppppppppppppppnnppppnpaaaappp",
    "tentative_best": "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnppnnnnnnnnnnnnnnnnnnnnnnnnpppppnnnnnnnnnnnnnnnnnnnnnnnpppppppppppppppnnnnnnnnnnnnnnnnnnnnnnnppppppppppnnnnnnnnnnnnnnnnnnnppppnnnnnnnnnnnnnnnnnnnnnnnppppppppnnnnnnnnnnnnnnnnnnnnnnnppnppnnnnnnnnnnnnnnnnnnnnnnnppppnnnnnnnnnnnnnnnnnnnnnnnnnppppppnnnnnnnnnnnnnnnnnnnnnnnnnppnnnnnnnnnnnnnnnnnnnnnnnnnpppppppnnnnnnnnnnnnnnnnnnnnnnnnnnpnnnnnnnnnnnnnnnnnnnnnnnnnpppnppppppppppppppnnppppnpaaaappp"
  },
  "last_pox_anchor": {
    "anchor_block_hash": "21a5dddd6468afd6190e5a8c566507d2aa102020bc9192325c067b1166c44275",
    "anchor_block_txid": "9b7da41e2add599bab7d7a6eac972a6999d08157db22a33466ea0ea9518d953a"
  }
}
```
</details>

And this is the block in question: https://explorer.hiro.so/block/0x1cf526975eec5a9ceff53c1926cfb50762b74fabf140474a3c53b716633676ca?chain=mainnet

**Comment by jferrant** [comment]
I have pulled the sbtc changes out of the next branch to enable easier testing. https://github.com/Trust-Machines/stacks-blockchain/pull/8 Hopefully working off that branch will make it easier to see what is wrong or if the sbtc changes are the culprit or not.

**Comment by netrome** [comment]
There seems to have been some progress on this, so I'll summarize here how I understand it:

**Problem**
The sBTC ops introduced in the `next` branch unintentionally causes a hard fork due to how the stacks block hash is computed.

We don't want to fork the Stacks chain for sBTC alpha

**Solution**
Ignore sBTC ops in the block hash computation.

For reference, here's a link to the resolution in the Stacks Discord: [link](https://discord.com/channels/621759717756370964/730814571517968436/1124042422553428079)

**Comment by netrome** [comment]
@stjepangolemac has fixed this in this commit: https://github.com/Trust-Machines/stacks-blockchain/pull/8/commits/04f01d375b5f5c0dd142873f36aece19f0f923b1
