### ISSUE TITLE
[signer-api] update bitcoin and stacks address types

### ISSUE THREAD

**Issue by jferrant** [Trust-Machines/stacks-sbtc#472]
Bitcoin and stacks addresses are currently stored as Strings and should be stored as the correct StacksAddress and BitcoinAddress types and converted to with an associated schema that have the hex, human readable, and byte content within them.

Definition of Done: 
The debit and credit addresses are converted to structs with the appropriate info in the Transaction Response.

**Comment by netrome** [comment]
Is this in progress still?

**Comment by netrome** [comment]
Closing as stale
