### ISSUE TITLE
Fix test `test-peg-in-op-return` 

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#490]
**Is your feature request related to a problem? Please describe.**

Test `test-peg-in-op-return` for `sbtc-peg-in-processor` contract has been commented out to merge big PR:

```clarity
;; @mine-blocks-before 5
;; @print events
(define-public (test-peg-in-op-return)
	(let ((result (contract-call? .sbtc-peg-in-processor complete-peg-in
			mock-peg-cycle ;; burn-height
			mock-op-return-tx-1 ;; tx
			0x ;; p2tr-unlock-script
			0x22 ;; header
			u1 ;; tx-index
			u1 ;; tree-depth
			(list 0x33 0x44) ;; wproof
			0x55 ;; ctx
			(list 0x55 0x66) ;; cproof
			)))
		(unwrap! result (err {err: "Expect ok, got err", actual: (some result)}))
		(asserts! (is-eq (get-sbtc-balance wallet-1) mock-value-tx-1) (err {err: "User did not receive the expected sBTC", actual: none}))
		(ok true)
	)
)
```

**Describe the solution you'd like**

Debug and fix this.

**Describe alternatives you've considered**

**Additional context**

**Comment by setzeus** [comment]
Looks like @MarvinJanssen already took care of this / removed the test in [#319 ](https://github.com/Trust-Machines/stacks-sbtc/commit/687004305e066f467eca93383f18e056d5c07df2#diff-35093f6f7a7fe946682eb2a5a72259da36ab8611ed7b3e033eae93fe783a0a79)

**Comment by jo-tm** [comment]
@set\ Yes, I mean we can add it again if it was failing.

**Comment by MarvinJanssen** [comment]
It was removed because the `OP_RETURN` peg-in path was removed from the protocol design spec.

**Comment by jo-tm** [comment]
Marvin: not supported anymore.
