### ISSUE TITLE
Decide on how to store pubkeys in registry

### ISSUE THREAD

**Issue by MarvinJanssen** [Trust-Machines/stacks-sbtc#493]
See https://github.com/Trust-Machines/stacks-sbtc/pull/319#discussion_r1234627016.

Store pub keys the Stacks way ({version, hashbytes}) or as scriptPubkey in the sBTC registry contract.

cc @FriendsFerdinand

**Comment by jo-tm** [comment]
@MarvinJanssen will add more context on this issue.

**Comment by MarvinJanssen** [comment]
Current consensus is to leave it as is for now, unless any strong reasons to go with the scriptPubKey format.

**Comment by FriendsFerdinand** [comment]
We can close this. I don't think there is any benefit if we ever need to convert `scriptPubKey` <-> {{ version, hashbytes }}
