### ISSUE TITLE
How to determine output index of the script path spend in Clarity?

### ISSUE THREAD

**Issue by MarvinJanssen** [Trust-Machines/stacks-sbtc#494]
See https://github.com/Trust-Machines/stacks-sbtc/pull/319/files#r1232256671.

Important for deposit and withdrawals, to prove that the proper script spend path was used to spend the output.

My suggestion is to supply the index as a parameter in the function call. Any potential issues with this @FriendsFerdinand?

**Comment by FriendsFerdinand** [comment]
I think that should work.
