### ISSUE TITLE
Signer product requirements

### ISSUE THREAD

**Issue by jferrant** [Trust-Machines/stacks-sbtc#496]
This issue is a story ticket tracking various product requirement for the Signer binary/API/UI. As product requirements are identified, they should be tracked here:

- [ ] #497
- [ ] #499
- [ ] #505
- [ ] #498

**Comment by andrerserrano** [comment]
Documented Signer product requirements [here](https://github.com/stacks-network/stacks/blob/master/sBTC/sbtc_signer.md).
