### ISSUE TITLE
Use Clarinet 1.7.0 Branch Coverage Feature

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#500]
based on @obycode suggestion

> [4:15 AM]brice: I was reading through these messages and just wanted to note that the just released clarinet 1.7.0 has some good improvements to code coverage, particularly in dealing with branches. https://github.com/hirosystems/clarinet/commit/13d450251575c40d81e155c29985cb481ae94a6d

**Comment by jo-tm** [comment]
This feature will avoid using Docker on the local testing.
Needs a keyword `branch` to work.

**Comment by jo-tm** [comment]
We need to enabled it on CI and see the numbers and table of branch coverage.

**Comment by friedger** [comment]
CI runs now clarinet 1.7.0 and there is the script `coverage-report.sh` that generates branch coverage.
