### ISSUE TITLE
[sbtc-mini] test-was-wtx-mined-internal-5 uses wrong data

### ISSUE THREAD

**Issue by friedger** [Trust-Machines/stacks-sbtc#507]
**Describe the bug**
test-was-wtx-mined-internal-5 uses wrong data for coinbase tx, header hash, etc.

**To Reproduce**
change bitcoin library so that was-tx-mined returns the txid and see that the test does not pass due to wrong data.

**Additional context**
https://github.com/friedger/clarity-bitcoin/commit/f641367ed163b8b9e3603ec9ae5078ad80824e33

**Comment by jo-tm** [comment]
@friedger : he is going to rebase before merging.
@jo-tm : must give friedger mantainer permissions to merge.

**Comment by friedger** [comment]
PR has been rebased
