### ISSUE TITLE
Confirm that the fix for stacks node freezes is valid

### ISSUE THREAD

**Issue by stjepangolemac** [Trust-Machines/stacks-sbtc#509]
Freezing happened because sBTC transactions were included in the consensus hash calculation. We've since filtered them out and the node has been working as expected.

I'm not sure if there are some downstream consequences of a fix like this and I would like to confirm with Jude or Aaron.

The fix commit, which is just a few lines long:
https://github.com/Trust-Machines/stacks-blockchain/commit/04f01d375b5f5c0dd142873f36aece19f0f923b1

**Comment by netrome** [comment]
This has been working nicely so far so it's confirmed.
