### ISSUE TITLE
[BLOCKER] Clarity Native Testing Better Annotations

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#519]

**Comment by jo-tm** [comment]
@setzeus pls write 1 line or 2 on this issue description.

**Comment by jo-tm** [comment]
@setzeus : working on test annotations for mining empty blocks to push the chain ahead an being in another window, blocking other tasks.

**Comment by jo-tm** [comment]
work in progress in test generation branch.

**Comment by friedger** [comment]
Definition of done:
clarity unit tests can be written in clarity like this:
```
(define-public (test-pox)
   ;; @external
   ;; @caller wallet_1
   (try! (contract-call? .pox-3 allow-contract-caller 'ST1234 none))

  ;; @mine-empty 5

  (contract-call? .sbtc-stacking-pool do-something)
) 
```
resulting in 
```
let block = chain.mineBlock([
		Tx.contractCall('ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.pox-3', 'allow-contract-caller', [...], callerAddress)]);
chain.mineEmptyBlock(5);
block = chain.mineBlock([
		Tx.contractCall('ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-stacking-pool_flow_test', 'test-pox_part2', [], callerAddress)]);
```

@MarvinJanssen @setzeus Is that the correct definition of done?

**Comment by friedger** [comment]
Or something like
```
(define-public (test-pox)
   ;; @new-block
   ;; @caller wallet_1
   (try! (contract-call? .pox-3 allow-contract-caller 'ST1234 none))

  ;; @mine-empty 5

  ;; @new-block
  (do-and-assert-something)

  ;; @mine-empty 5

  (do-and-assert-something)
) 
```

resulting in

```
let block = chain.mineBlock([
		Tx.contractCall('ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.pox-3', 'allow-contract-caller', [...], callerAddress)]);
block.receipts[0].expectOk();

chain.mineEmptyBlock(5);
block = chain.mineBlock([
		Tx.contractCall('ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-stacking-pool_flow_test', 'do-and-assert-something', [], callerAddress)]);

chain.mineEmptyBlock(5);
block = chain.mineBlock([
		Tx.contractCall('ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-stacking-pool_flow_test', 'do-and-assert-something', [], callerAddress)]);

```

**Comment by friedger** [comment]
That means test-functions can be tests describing a flow or normal tests as we have now.

Flow tests can contain only simple functions calls:
* as local functions
* as `contract-call?` calls wrapped in try

Flow tests can contain the following commented annotations:
* `;;@mine-empty n` - resulting in n empty blocks
* `;;@new-block` - starting a new block

Both annotations are closing an open block.

**Comment by MarvinJanssen** [comment]
I personally think splitting function context is dangerous. What about let variables?

```clarity
(define-public (test-pox)
   (let (some-let-var u1))
   (try! (contract-call? .pox-3 allow-contract-caller 'ST1234 none))

  ;; @mine-empty 5

  (contract-call? .sbtc-stacking-pool do-something some-let-var)
  )
) 
```

How will you deal with it?

My preference is creating test groups:

```clarity
;; @test-group pox
(define-public (test-group-pox-setup)
  ;; .. stuff
)

;; @test-group pox
;; @mine-blocks-before 4
(define-public (test-group-pox-do-commit)
  ;; .. stuff
)

;; @test-group pox
;; @mine-blocks-before 4
(define-public (test-group-pox-wrap-up)
  ;; .. stuff
)
```

**Comment by friedger** [comment]
@MarvinJanssen The important part is that we can make contract calls where contract-caller is tx-sender
```
   (try! (contract-call? .pox-3 allow-contract-caller 'ST1234 none))
```

test functions have the restrictions that they can only contain function calls and contract calls in very specific formats nothing else. See #613 

If we really want to do cool stuff we should use rust clarity::vm analysis package (like clar2wasm)

**Comment by MarvinJanssen** [comment]
>test functions have the restrictions that they can only contain function calls and contract calls in very specific formats nothing else. See https://github.com/Trust-Machines/stacks-sbtc/pull/613

We did not define those restrictions (yet). In any case, the problem I have with it is that we break the expected execution path of a function.

Compare:

```clarity
(define-public (test-sign-pre-register)
 	(begin
         ;; @continue
         (unwrap! (contract-call? .pox-3 mock-set-stx-account 'ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5 {locked: u10000000000000, unlock-height: u4200, unlocked: u10000000000000}) (err u111))
         ;; @continue
         (unwrap! (contract-call? .pox-3 allow-contract-caller 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-stacking-pool none) (err u112))
         ;; @continue
         (try! (check-pox-info))
         ;; @mine-blocks-before 5
 		(try! (check-sign-pre-register))
         ;; @mine-blocks-before 2100
 		(try! (check-sign-register))
         (ok true))
 )
```

To the following:

```clarity
;; @group sign-pre-register
(define-public (test-sign-pre-register-step1)
 	(begin
		(unwrap! (contract-call? .pox-3 mock-set-stx-account 'ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5 {locked: u10000000000000, unlock-height: u4200, unlocked: u10000000000000}) (err u111))
		(unwrap! (contract-call? .pox-3 allow-contract-caller 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-stacking-pool none) (err u112))
		(try! (check-pox-info))
		(ok true)
	)
 )

;; @group sign-pre-register
;; @mine-blocks-before 5
(define-public (test-sign-pre-register-step2)
 	(check-sign-pre-register)
)

;; @group sign-pre-register
;; @mine-blocks-before 2100
(define-public (test-sign-pre-register-step3)
 	(check-sign-register)
)

```

**Comment by friedger** [comment]
@MarvinJanssen With your proposal the alphabetic order would define the execution path?

**Comment by MarvinJanssen** [comment]
I would say the order in which the functions are defined in the file.

Also we should enforce groups to start with `test-group-` and disallow non-grouped tests to start with name `test-group-`.

Direct calls are quite problematic. How would you feel about this?

```clarity
;; @group sign-pre-register
;; @direct-call ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5 (contract-call? .pox-3 mock-set-stx-account 'ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5 {locked: u10000000000000, unlock-height: u4200, unlocked: u10000000000000})
;; @direct-call ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5 (contract-call? .pox-3 allow-contract-caller 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-stacking-pool none)
(define-public (test-sign-pre-register-step1)
 	(begin
		(try! (check-pox-info))
		(ok true)
	)
 )
```

Pattern:
```clarity
;; @direct-call <tx-sender> <s-expression>
```

Too much meta-programming?

**Comment by friedger** [comment]
The contract calls in the comments makes it hard to navigate the code and find typos etc.
Until we have better tool support for that, I would not go for that.

**Comment by MarvinJanssen** [comment]
Understood. Let's stick with what you did. We just have to make sure to explain the limitations of flow test functions. (Also we will not be able to call them in a `clarinet console` session which is unfortunate. I really wonder if we can come up with a better solution to the `contract-caller` issue.)

**Comment by friedger** [comment]
👍

**Comment by jo-tm** [comment]
@friedger @MarvinJanssen let's continue the discussion on `contract-caller` issue on issue #632 because this one is closed.
