### ISSUE TITLE
Mini-v1: Voting

### ISSUE THREAD

**Issue by setzeus** [Trust-Machines/stacks-sbtc#528]
**Overview.**
This project covers the simplest voting mechanic for registered sBTC stackers/signers & maps to row 23 of the [frozen Stacks 3.0 / sBTC Product-Eng Roadmap
](https://docs.google.com/spreadsheets/d/1DwLNts95_4olTXKFI1sV7kF47UlvbpmdADfhUtZ9xJA/edit#gid=1434620742)

**User Stories**
- [x] As a registered Stacker/Signer, I want to vote for the next cycle sbtc-wallet
- [x] As a registered Stacker/Signer, I want to vote for the winning next cycle sbtc-wallet & aggregate-commit

**Comment by jo-tm** [comment]
working on unit flow testing, but impl done in #578
