### ISSUE TITLE
[sbtc-alpha] coordinator needs to persist DKG polynomials or derived values

### ISSUE THREAD

**Issue by xoloki** [Trust-Machines/stacks-sbtc#536]
**Describe the bug**
Current `frost-coordinator` expects that the DKG polynomials are available during the signing process.  They are used to generate the aggregate public key, and public keys for each key share; the latter keys are needed to validate signature shares from the signers.  

This is not a problem during unit or integration testing, since in those contexts we do both DKG and sign operations. However, in a production environment there are no guarantees that coordinator will never go down.

The sBTC alpha contract currently stores the aggregate public key, but it does not store the share public keys, or the polynomials themselves.  The amount of storage needed depends on what we choose to store:

For `N` keys and threshold `T` (where `T < N`), storing all polynomials will be `O(N*T)`.  Storing only the aggregate polynomial will be `O(T)`, and storing the share public keys will be `O(N)`.  So if the only consideration is space required, then we should store the aggregate polynomial.

However, if we store the aggregate polynomial then we will have to calculate the share public keys during every signing operation.  This roughly doubles the time required to sign.  So the best tradeoff appears to be storing the share public keys.

Since we are storing the aggregate public key in the contract, it makes the most sense to store the share public keys there as well.

**To Reproduce**
1. Run DKG using `stacks-coordinator` and `stacks-signer`.  This will persist the aggregate public key in the contract.
2. Restart `stacks-coordinator`, then try to do a signing round.  The aggregate public key will load from the contract, but not the polynomials.
3. Signing will fail

**Expected behavior**
Signing should work after a `stacks-coordinator` restart.

**Comment by netrome** [comment]
Note: The `frost-coordinator` config currently has a `frost_state_file` field which is unused. Perhaps it makes sense for alpha to persist the coordinator state in the filesystem and not the contract, since this is internal parameters which are not needed from anyone else than the coordinator - unlike the aggregate public key which must be obtainable from anyone using the system.
