### ISSUE TITLE
[stacking-pool] penalty-unhandled-request does not lock stackers to burn address

### ISSUE THREAD

**Issue by friedger** [Trust-Machines/stacks-sbtc#547]
**Describe the bug**
The function `penalty-unhandled-request` does not lock any stx, it only calls stack aggregation commit for the burn address.

**To Reproduce**
Inspect `penalize-helper`
https://github.com/Trust-Machines/stacks-sbtc/blob/bb5ed58befb5305f6ea4688e2e6efde8f328c0f7/sbtc-mini/contracts/sbtc-stacking-pool.clar#L596

**Expected behavior**
stx are locked for burn address.
delegate-stx-extend should be called with the burn address.

Instead of burning btc we should not call stack-aggregation-commit for the burn address, then the burn address won't get any rewards and the community of stackers will benefit more.

**Comment by jo-tm** [comment]
@setzeus bug report from friedger, if you need clarification we can discuss next Tuesday.

**Comment by setzeus** [comment]
@friedger made a commit here to address : https://github.com/Trust-Machines/stacks-sbtc/tree/sbtc-mini-stacking-pool-quick-fixes

Updated (penalize-helper ...) by removing the aggregate-commit & by adding a penalize-mass-delegate-stack-extend function to fold through & instead delegate-stack-extend for every stacker. 

Is this the solution you were envisioning?

**Comment by friedger** [comment]
Yes, that could work as long as stackers don't revoke.

In pox-4, we feed to remove that revoke function.

You need to check the results of the extend function @setzeus

**Comment by jo-tm** [comment]
also included in #578

**Comment by friedger** [comment]
fixed by https://github.com/Trust-Machines/stacks-sbtc/pull/578
