### ISSUE TITLE
[stacking-pool] vote-for-threshold-wallet-candidate does not extend stacking

### ISSUE THREAD

**Issue by friedger** [Trust-Machines/stacks-sbtc#548]
**Describe the bug**
vote-for-threshold-wallet-candidate only calls stack-aggregation-commit and does not call delegate-stack-extend

**To Reproduce**
Inspect function https://github.com/Trust-Machines/stacks-sbtc/blob/a9157761c9e6f7be76e76a38c72aa36a822086f2/sbtc-mini/contracts/sbtc-stacking-pool.clar#L437

**Expected behavior**
voting means that the user locks their stx for the new wallet, therefore the stacking must be extended.

stack-aggregation-commit call ensures that the wallet eventually receives stacking rewards. Voters have only 1 vote, no way to change.

**Comment by setzeus** [comment]
Just double-checking here the logic here. It's okay that a registered stacker extends for the (eventually) losing POX address because the delegate aggregating committing overrides that POX? 

Reviewing POX-3 logic but want to make sure I understand.

**Comment by friedger** [comment]
Once voted for a loosing wallet, there is no way back. The commit only ensure that the stx are earmarked for earning rewards, it does not change the locking state. 

All stackers should agree on one wallet and then do the vote. 

Is the new peg wallet deterministic in some way?

**Comment by setzeus** [comment]
Unsure how FROST is used to generate the peg-wallet candidates. 

Reviewing (delegate-stack-extend ...) I'm wondering if there's any reason we can't just mass delegate-stack-extend the moment a successful wallet (> 70% consensus) is voted upon?

As long as we're recording that a stacker voted, once a vote is successful in consensus we can (delegate-stack-extend ...) to the winner for everyone regardless of who they voted for - any reason this approach wouldn't work?

**Comment by friedger** [comment]
Yes, that can work. Good idea!

**Comment by friedger** [comment]
We have to see how many delegate call we can get into one txs resource wise

**Comment by jo-tm** [comment]
will be dealt in #578 a function take care of this. Kudos to friedger.

**Comment by friedger** [comment]
fixed by #578
