### ISSUE TITLE
[stacking-pool] Add test for stacking

### ISSUE THREAD

**Issue by friedger** [Trust-Machines/stacks-sbtc#549]
**Is your feature request related to a problem? Please describe.**
clarinet unit tests does not support stacking properly, stx-account does not handle locked amount

**Describe the solution you'd like**
Implement mock behaviour in .pox-3 that allows tests to set locked amount manually.

**Describe alternatives you've considered**
Use integration tests on devnet.

**Additional context**
https://github.com/Trust-Machines/stacks-sbtc/pull/544#issuecomment-1633579268

**Comment by jo-tm** [comment]
will be solved in a branch from @setzeus , no PR yet.

**Comment by friedger** [comment]
fixed by #613
