### ISSUE TITLE
Verify that the sBTC bridge uses the wrong key for signing withdrawal payloads

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/stacks-sbtc#561]
Currently we are assuming that we have a bug in the sBTC bridge app ([issue link](https://github.com/Stacks-Builders/sbtc-bridge-web/issues/181)), where it is using the wrong key to sign the withdrawal request payload. However, as far as I know we have not tested if this is actually the case or if we just have failed to withdraw using the sbtc-cli with the wrong keys. So just to verify our assumption, it's worth testing it.

### Definition of done
We have tested doing a withdrawal from the sBTC bridge app, and verify that the burn address in the resulting burn call is not the same as the wallet account we're using to sign it.

**Comment by netrome** [comment]
Blocked on https://github.com/Stacks-Builders/sbtc-bridge-web/issues/184

**Comment by jferrant** [comment]
Related to https://github.com/Trust-Machines/stacks-sbtc/issues/556

**Comment by netrome** [comment]
This was not the case and has been resolved.
