### ISSUE TITLE
[sbtc-mini] sbtc-stacking-pool / signer-pre-register-test should be read only

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/stacks-sbtc#562]
**signer-pre-register-test**

`sbtc-stacking-pool.signer-pre-register-test` does not change state - should be read only.

**Comment by setzeus** [comment]
Copy @radicleart . This was a placeholder function for developing a generation script on my end. Will remove in next PR.

**Comment by jo-tm** [comment]
PR #578 will fix this.

**Comment by friedger** [comment]
fixed by #578
