### ISSUE TITLE
[sbtc-mini] sbtc-stacking-pool signer minimal design

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/stacks-sbtc#563]
**signer-minimal is 0**

It's not possible to pre register (`signer-pre-register`) atm because variable signer-minimal is 0 and has no setter.

It's possible to pass amount-ustx=0 but the method calls `contract-call? .pox-3 delegate-stx` and so passes 0 to pox-3 - not sure this make sense?

**Comment by friedger** [comment]
The amount sent must be greater than the minimum @radicleart

**Comment by radicleart** [comment]
The assertion is 

```(asserts! (>= amount-ustx (var-get signer-minimal)) err-not-enough-stacked)```

**Comment by friedger** [comment]
Therefore, any amount greater than 0 (signer minimal) is good

**Comment by radicleart** [comment]
Yep - i can work around it - the issue is about the code - should it call the pox-3 contract with amount=0 and should there be a setter for signer-minimal, maybe it should be a const ?

**Comment by friedger** [comment]
The minimum could be something like the previous cycle's slot amount + 20%

**Comment by friedger** [comment]
A minimum of 0 does not make sense. It could be used to indicate that the pool is not activated

**Comment by radicleart** [comment]
Sorry - i'm saying as it stands in the code the min is 0 and the register call accept 0 and call the pox contract to delegate - this was the bug i was trying to document.

**Comment by friedger** [comment]
> not one slot per signer.

That means that new signers do not get any rewards in the first cycle. Is that intended?

**Comment by MarvinJanssen** [comment]
From my reading and memory of the original design, new signers should get a reward to their own address when they register. Later when they vote, they automatically change the target to the peg wallet address. Additionally, the minimum to register should lead to at least one slot. I am not sure if the spec included the situation of when someone registers with sufficient amount, but in the end the stacking minimum goes up and the new signer now has no slots.

**Comment by friedger** [comment]
Technically, it is not required for a pox-address of a pool to meet any minimum.

We can leave it to the new stacker to decide whether they want to try and get some rewards by locking as much as she thinks it's appropriate for 1 slot.

**Comment by MarvinJanssen** [comment]
Not for a pool right, but in the sBTC design spec it was made to be a requirement.

**Comment by friedger** [comment]
What is the reason for the requirement? I don't see a need for it. We should adapt the spec.

**Comment by MarvinJanssen** [comment]
It was so that they could not unlock the STX and then have no skin in the game. But as you pointed out in your amendment to the master doc, tokens locked by a pool operator do not unlock. It therefore makes sense to remove the requirement. I am not sure if a minimum is still a requirement at all. I think it also helps to keep the number of signers at a management amount. (If you can join with 1 STX you could see a lot of signers that need to participate in FROST.)

**Comment by friedger** [comment]
We should require 1m STX (around 10 slots) to have some support sbtc. 1m STX / 100 = 10k STX minimum

**Comment by MarvinJanssen** [comment]
Sounds OK to me but let us bring that up in the next sBTC meeting. Requiring slots instead of STX would make the minimum dynamic.

**Comment by jo-tm** [comment]
Use the sBTC Docs Repo for this discussion and decisions cc/ @netrome

**Comment by friedger** [comment]
Proposal from docs is implemented in https://github.com/Trust-Machines/stacks-sbtc/pull/629
