### ISSUE TITLE
[stacking-pool] Wrong epoch and pox version in Clarinet.toml

### ISSUE THREAD

**Issue by friedger** [Trust-Machines/stacks-sbtc#569]
**Describe the bug**
Clarinet toml uses epoch 2.1 but wants to use pox-3. Requirement is set to pox-2

Settings need to be updated for tests with devnet.

**To Reproduce**
See Clarinet.toml
https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/Clarinet.toml#L16

**Expected behavior**
Use epoch 2.4

**Comment by jo-tm** [comment]
will be fixed by #570, and @jo-tm will review this.

**Comment by setzeus** [comment]
Is a different version of Clarinet required for 2.4? I'm blocked now since pulling this in.

**Comment by friedger** [comment]
Clarinet 2. There is no clarinet 3

**Comment by setzeus** [comment]
Maybe some confusion here.

**What I Did**
Pulled from main to catch-up, CDd into "sbtc-mini" in #578 & typed in "clarinet console"

**What I Expected**
To run clarinet & see a log of all contracts, functions, etc.

**What Happened**
"error: syntax errors in Clarinet.toml
epoch field invalid (value supported: 2.0, 2.05, 2.1)"
