### ISSUE TITLE
[stacking-pool] Make stacking pool work on devnet with pox-3

### ISSUE THREAD

**Issue by friedger** [Trust-Machines/stacks-sbtc#571]
**Is your feature request related to a problem? Please describe.**
Integration tests can be done with `clarinet integrate` and pox-3.

**Describe the solution you'd like**
Adapt the code so that integration tests with the sbtc-signer ui can work together.

This issue is about collection changes required to make this happen. Similar changes would be needed for testnet as well.

**Comment by friedger** [comment]
Change
* .pox-3 to ST000..pox-3
* change length of voting/transfer/penalty periods

**Comment by jo-tm** [comment]
work in progress in another branch.
