### ISSUE TITLE
[sbtc-mini] Design Discussion: Signer Minimal

### ISSUE THREAD

**Issue by setzeus** [Trust-Machines/stacks-sbtc#583]
Opened this issue to continue a conversation first surfaced by @radicleart & later evolved into a larger conversation for the Clarity work group. 

The topic revolves around the minimal amount of STX required to stack for both the aggregate stacking/signing pool & the individual stacker/signer. 

Below is my understanding of the ideal logic for both:

**1. Aggregate Stacking/Signing Pool Minimum**
Since we can't know the slot minimum ahead of time, the proposal here is for a dynamic pool-minimum that is a function of the previous cycle minimum plus some % (10%? 20%?).

**2. Individual Stacker/Signer Minimum**
Though this is also open for discussion/change, the stacking pool map is currently defined by a list of 100 principals. The contract currently has a var (signer-minima) that doesn't have a setter. A few open questions such as: 

- Do we also _need_ a minimum for these (up to) 100 principals?
-  If so, how much? (ideally should be a function of 1.^)

**Comment by friedger** [comment]
Duplicate to #563
