### ISSUE TITLE
Cargo "--release" flag results in infinite recursion from "bdk" dependency.

### ISSUE THREAD

**Issue by AshtonStephens** [Trust-Machines/stacks-sbtc#599]
# Cargo build with --release flag results in infinite recursion error
We're getting the following error when compiling with with the `--release` flag because of a possible error in miniscript what we import from bdk:

```
error[E0275]: overflow evaluating the requirement `F: FnMut<(&Pk,)>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`miniscript`)
  = note: required for `&mut F` to implement `FnMut<(&Pk,)>`
  = note: 128 redundant requirements hidden
  = note: required for `&mut &mut &mut &mut &mut &mut &mut &mut &mut ...` to implement `FnMut<(&Pk,)>`
```

The miniscript team is currently working on a fix for miniscript version `9.x` that we can track in https://github.com/rust-bitcoin/rust-miniscript/pull/566. The issue first occurred a while ago but has only recently become a problem because rustc stable now includes a change that causes this to happen (https://github.com/rust-lang/rust/issues/110475). Unclear if it's an issue with rustc or mini script, but it doesn't really matter.

## What needs to be done

1. Temporarily disable the matrix options with `--release` in our rust github workflow so it can continue to run in our pipeline without errors.
2. Once https://github.com/rust-bitcoin/rust-miniscript/pull/566 is closed we need to look at our dependencies and see what it takes to consume their fix. ( Note: if it has been a week without a solution perhaps we see if we can help resolve the issue )
3. Re-enable `--release` option in rust matrix

## Acceptance criteria

We run matrix tests with `--release` flag without removing any test functionality

**Comment by sergey-shandar** [comment]
Another option: temporary use older version of Rust

**Comment by AshtonStephens** [comment]
Release build re-enabled. Closing ticket.
