### ISSUE TITLE
make error codes unique across contracts

### ISSUE THREAD

**Issue by friedger** [Trust-Machines/stacks-sbtc#618]
**Describe the feature**
As defined in https://docs.google.com/spreadsheets/d/1udTG-fkyvj6bDZhN6NKYedYxBlV1Ycftqu9eM3_rHeA/edit#gid=0 all error codes should be unique across sbtc contracts. The error codes should use the defined code spaces.

**Comment by jo-tm** [comment]
@friedger is this closed?

**Comment by MarvinJanssen** [comment]
Yes it is checked by a run script now. I will close.
