### ISSUE TITLE
[Main] Activate a Devnet Deployment for Integration with Signer

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#653]
Testnet has 1 week wait for testing, then we must start with Devnet version.

**Comment by jo-tm** [comment]
This will fix https://github.com/Trust-Machines/stacks-sbtc/issues/234

**Comment by friedger** [comment]
## How to launch devnet ##
install (clarinet)[https://github.com/hirosystems/clarinet] 
checkout `sbtc-mini/631-deployments`

```
cd sbtc-mini
# Press N when asked to overwrite deployment script
./scripts/integration-test.sh
```
See clarinet dashboard what until local devnet is ready (around block 137)
![image](https://github.com/Trust-Machines/stacks-sbtc/assets/1449049/44d219ae-3516-47a3-aa4b-d3e6dc6a8f6a)

In a second console run the bootstrap call
```
# Press Enter when asked to overwrite
clarinet deployments apply deployments/bootstrap.devnet-plan.yaml
``` 
In first console, press N to produce a block and see how the tx is processed.

See `settings/Devnet.toml` for seed phrases for pre-filled accounts.

There are more deployments for stacking, voting, etc. in https://github.com/Trust-Machines/stacks-sbtc/pull/655

**Comment by jo-tm** [comment]
I will include this in the `./sbtc-mini/README.md`

**Comment by friedger** [comment]
@jo-tm Better to collect this information in sbtc-docs: https://github.com/stacks-network/sbtc-docs/pull/59

**Comment by jo-tm** [comment]
Fixed by https://github.com/Stacks-Builders/sbtc-bridge-web/issues/209
