### ISSUE TITLE
Rename peg-out and peg-in contracts to their new names.

### ISSUE THREAD

**Issue by MarvinJanssen** [Trust-Machines/stacks-sbtc#654]
Rename peg-out and peg-in contracts to their new names.

**Comment by friedger** [comment]
What are the new names?

**Comment by MarvinJanssen** [comment]
Deposit and withdrawal.

**Comment by friedger** [comment]
Is there a new name for peg-transfer?

**Comment by friedger** [comment]
peg-transfer -> hand-off
