### ISSUE TITLE
How opinionated should the sBTC registry contract be?

### ISSUE THREAD

**Issue by MarvinJanssen** [Trust-Machines/stacks-sbtc#682]
A conversation that came up a few times. See for example: https://github.com/Trust-Machines/stacks-sbtc/pull/595#discussion_r1295413358.

The question is how opinionated should the registry be? The point of the registry is to have a single contract to store protocol state. It allows us to more easily upgrade business logic while keeping protocol state. However, the registry currently does have some logic in terms of withdrawal status etc.. On the flip side, the registry stores withdrawal expiration height but does not enforce it itself. The idea here was that a (future) different protocol contract would be able to handle expired withdrawals differently if the protocol requires it at some point in time.

This issue is not a explicit bug report of feature suggestion but more to start a conversation about how opinionated the registry should be.

**Comment by radicleart** [comment]
A birds eye description of the design / roles and responsibilities of the contracts (or link to something pre-existing) at the level of the  to the error code table in the readme - will be helpful.

Are there analogies with the executor dao in terms of design patterns and composability? Can i think about the pool, token, hand-off and processor contracts akin to extensions ?

**Comment by MarvinJanssen** [comment]
Outdated.
