### ISSUE TITLE
Implement Clarity Contracts Property Testing for sBTC-token.clar Contract

### ISSUE THREAD

**Issue by setzeus** [Trust-Machines/stacks-sbtc#691]
*It's understood that we're moving off of this repository/branch in the near term future*

This ticket is for @moodmosaic to begin writing up property tests for the sBTC-token.clar contract. The goal of this issue to make this a transparent, collaborative testing implementation so that we can considering carrying this over for other contracts. 

We've specifically picked sBTC-token.clar since we assume it's the most-likely locked contract that will persist through builds:

https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/contracts/sbtc-token.clar

**Comment by moodmosaic** [comment]
It looks like the very first run of the test-suite yields a few errors, and subsequent runs succeed. Is this a known issue? /cc @friedger

```
$ ./scripts/test.sh
rm: cannot remove '.test/*': No such file or directory
./ext/generate-tests.ts => running script ... FAILED (69ms)

 ERRORS

running script => https://deno.land/x/clarinet@v1.7.0/index.ts:334:10
error: AssertionError: Test case is leaking async ops.

 - 3 async operations to op_write_file_async were started in this test, but never completed. The operations were started here:
    at Object.opAsync (deno:core/01_core.js:158:42)
    at writeFile (deno:clarinet-cli/js/40_write_file.js:37:18)
    at Object.writeTextFile (deno:clarinet-cli/js/40_write_file.js:70:12)
    at Object.fn (file:///C:/Snapshot/dev/stacks/stacks-sbtc/sbtc-mini/ext/generate-tests.ts:50:9)

 FAILURES

running script => https://deno.land/x/clarinet@v1.7.0/index.ts:334:10

FAILED | 0 passed | 1 failed (2s)

./ext/generate-flow-tests.ts => running script ... FAILED (51ms)

 ERRORS

running script => https://deno.land/x/clarinet@v1.7.0/index.ts:334:10
error: AssertionError: Test case is leaking async ops.

 - 5 async operations to op_write_file_async were started in this test, but never completed. The operations were started here:
    at Object.opAsync (deno:core/01_core.js:158:42)
    at writeFile (deno:clarinet-cli/js/40_write_file.js:37:18)
    at Object.writeTextFile (deno:clarinet-cli/js/40_write_file.js:70:12)
    at Object.fn (file:///C:/Snapshot/dev/stacks/stacks-sbtc/sbtc-mini/ext/generate-flow-tests.ts:72:12)
 
 FAILURES

running script => https://deno.land/x/clarinet@v1.7.0/index.ts:334:10

FAILED | 0 passed | 1 failed (1s)

./.test/sbtc-btc-tx-helper_test.ts => test-hashbytes-to-scriptpubkey-with-invalid-version: test error handling for hashbytes to scriptPubkey with invalid version ... ok (82ms)
./.test/sbtc-controller_test.ts => test-upgrade-principals: Upgrade principals must be contract principals ... ok (92ms)
./.test/sbtc-btc-tx-helper_test.ts => test-hashbytes-to-scriptpubkey-with-P2WPKH-version: Convert hashbytes to scriptPubkey with non-p2tr version ... ok (86ms)
[...]

ok | 100 passed | 0 failed (16s)
```

I can provide the full log if needed.

**Comment by friedger** [comment]
The first one, is just a warning.

The second error happens sometimes. I don't know what is the cause.

**Comment by friedger** [comment]
@moodmosaic it allows the test contract to act as a protocol contract, that is the test contract has high permissions.

**Comment by moodmosaic** [comment]
@friedger, thanks. What protocol contracts do? Where can I read about the concept?

**Comment by friedger** [comment]
This is probably the best source https://github.com/stacks-network/sbtc-docs/blob/sbtc-dr-first-draft/src/sbtc-releases/sbtc-dev.md

@moodmosaic

It is all about sbtc mini which will never be released

**Comment by moodmosaic** [comment]
@friedger, thank you. I only need to go through that doc so I can understand the current testing structure, in order to make each test case autonomous (that is, inline any setup phase), with the goal of having an autonomous set of test cases that can be then randomly executed/fuzzed (as done in https://github.com/hirosystems/clarity-starter/issues/1 for example).

**Comment by moodmosaic** [comment]
Actually, if that's the case, I guess we should start with a decent property test suite around the SIP010 trait, and skip the protocol tests? /cc @AshtonStephens @MarvinJanssen @friedger @setzeus

**Comment by moodmosaic** [comment]
@friedger 

>It is all about sbtc mini which will never be released

Are the sBTC token and the sBTC protocol affected by this?

**Comment by friedger** [comment]
They are slightly different, see https://github.com/stacks-network/sbtc/tree/master/romeo/asset-contract

**Comment by friedger** [comment]
Note that mint and burn use on-chain verification

**Comment by moodmosaic** [comment]
From what I can see in https://github.com/stacks-network/sbtc/tree/master/romeo/asset-contract, only the contract deployer can mint. Then, I believe, the on-chain verification happens through event(s)?

**Comment by AshtonStephens** [comment]
@friedger It looks like @moodmosaic's work is impacted by a recent change in [`asset.clar`](https://github.com/stacks-network/sbtc/commit/ec6eddb0b4620ddad7a1cc8c5e1cbff789acc16f#diff-b34352c7aba15c5350fc8de3ba7963f1c7334b5bb6d22494ac6621381dc1bf03). 

Are there going to be more changes to that interface in the near future?

**Comment by friedger** [comment]
Yes, there is a PR about security improvements by @jo-tm

**Comment by friedger** [comment]
But the api should be the same.

**Comment by moodmosaic** [comment]
Thanks @friedger and @AshtonStephens. From what I see, most of the changes I have to make (in the property tests, on my branch) is around the `mint` function. If I need help, I'll let you know.
