### ISSUE TITLE
Security review of smart contracts (asset, token, clarity-bitcoin)

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/stacks-sbtc#692]
Do internal security review of the following contracts for sBTC:

- Find security Bugs in the sBTC Token smart contract sBTC Token.

* https://github.com/stacks-network/sbtc/tree/master/romeo/asset-contract/ (https://github.com/stacks-network/sbtc/commit/c8a7891b7ba11c074c434a7c93dd2944ed7cda74)
  * [x] Access control
  * [x] Timestamp dependence
  * [x] Cross-function vulnerabilities  
  * [x] Number rounding errors
  * [x] Denial of service / logical oversights
  * [x] Arbitrary token minting
  * [x] Transaction-ordering dependence
  * [x] Mishandled exceptions and call stack limits
  * [x] Unsafe external calls
  * [x] Centralization of power
  * [x] Business logic contradicting the specification
  * [x] Code clones, functionality duplication
  * [x] Usage cost
  * [x] Checks-Effects-Interaction Pattern
  * [x] Untested Guards/Preconditions/Business Logic.

* https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/contracts/sbtc-token.clar [[83ce95b](https://github.com/Trust-Machines/stacks-sbtc/commit/83ce95bb860b3b6151d4812f50174bea85ca883e)]
  * [x] Access control
  * [x] Timestamp dependence
  * [x] Cross-function vulnerabilities  
  * [x] Number rounding errors
  * [x] Denial of service / logical oversights
  * [x] Arbitrary token minting
  * [x] Transaction-ordering dependence
  * [x] Mishandled exceptions and call stack limits
  * [x] Unsafe external calls
  * [x] Centralization of power
  * [x] Business logic contradicting the specification
  * [x] Code clones, functionality duplication
  * [x] Usage cost
  * [x] Checks-Effects-Interaction Pattern
  * [x] Untested Guards/Preconditions/Business Logic.

- Find security Bugs in the sBTC Token smart contract sBTC Controller.

* https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/contracts/clarity-bitcoin.clar [[83ce95b](https://github.com/Trust-Machines/stacks-sbtc/commit/83ce95bb860b3b6151d4812f50174bea85ca883e)]
  * [x] Access control
  * [x] Timestamp dependence
  * [x] Cross-function vulnerabilities  
  * [x] Number rounding errors
  * [x] Denial of service / logical oversights
  * [x] Arbitrary token minting
  * [x] Transaction-ordering dependence
  * [x] Mishandled exceptions and call stack limits
  * [x] Unsafe external calls
  * [x] Centralization of power
  * [x] Business logic contradicting the specification
  * [x] Code clones, functionality duplication
  * [x] Usage cost
  * [x] Checks-Effects-Interaction Pattern
  * [x] Untested Guards/Preconditions/Business Logic.

**Comment by setzeus** [comment]
Just making sure, are you & @moodmosaic working together on this? So I can remove #691

**Comment by jo-tm** [comment]
@setzeus @moodmosaic I am working on this with a security checklist, is not for testing.

**Comment by jo-tm** [comment]
🟠 TMS-02 [Medium/Unresolved] No Function to Change the Contract Owner
- Description: The contract owner is set to tx-sender during the contract deployment, and there is no function to change the contract owner. If the contract owner loses access to their account or is compromised, the contract lacks a means to change the owner, leading to potential loss of control over the contract functionalities.
- File(s): asset.clar
- Recommendation: Implement a function to securely change the contract owner.  
```clarity
(define-public (set-new-owner (new-owner principal))
  (begin
    (asserts! (is-contract-owner) err-forbidden)
    (var-set contract-owner new-owner)
    (ok true))
)
```

**Comment by jo-tm** [comment]
🟠 **[Medium/Unresolved]  Access Control Using Global `tx-sender`**
- Description: In the context of phishing attempts with intermediary contracts, or untrusted DeFi composition of smart contracts (the whole point of DeFi is to combine untrusted contracts), the use of `tx-sender` is unacceptable for access control and token transfers (without as-contract wrapper). Line 53 with (asserts! (is-eq tx-sender sender) err-forbidden) is vulnerable. Also line 93 in function `is-contract-owner`. Read a short blog post from CoinFabrik (https://blog.coinfabrik.com/tx-sender-in-clarity-smart-contracts/) for a more detailed explanation.
- File(s): asset.clar
- Recommendation: Use variable `contract-caller` that is local and it cannot be improperly encapsulated as tx-sender can be. In some cases with transfer the solution to this problem is to use the function `as-contract` to limit tx-sender and contract-caller to the value of the contract context.  
```clarity
(define-private (is-contract-owner)
  (is-eq (var-get contract-owner) contract-caller)
)
```

**Comment by jo-tm** [comment]
Fixes for `asset.clar` from Alpha Romeo proposed here: https://github.com/stacks-network/sbtc/issues/118

**Comment by jo-tm** [comment]
🟢 [Informational/Unresolved]  **Lack of Event Logs** 
- _Description:_ The contract does not have a logging mechanism. Even though Stacks and Clarity do not natively support events you can use the `print` function for logging. This can be important for tracking actions, especially for auditing. This is informational because even it may not directly impact the security of the contract, they are points to consider for better functionality and auditability.
- _Files affected:_ [sbtc-token.clar](https://github.com/Trust-Machines/stacks-sbtc/blob/main/sbtc-mini/contracts/sbtc-token.clar)
- _Recommendation:_ use `print` function to log records like for example `(print {type: "transfer", token-id: token-id, amount: amount, sender: sender, recipient: recipient})`
