### ISSUE TITLE
Collect initial ideas and thoughts

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/stacks-sbtc#82]

**Comment by igorsyl** [comment]
My [How to Work with Igor](https://docs.google.com/document/d/1YPg9sq7Si7Axiz7FAHcLyq2Incd0Iz5zDOZqbA43-Kc/edit) public document used for external collaboration.

**Comment by netrome** [comment]
Oh nice! I'll add one about me :)


Den mån 20 feb. 2023 kl 16:19 skrev Igor Sylvester ***@***.***
