### ISSUE TITLE
Degens: Decentralized Mining Pool

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/stacks-sbtc#93]
https://stacks-degens.gitbook.io/decentralized-mining-pool/
https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/790
https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/821
https://stacksdegens.notion.site/Decentralized-Mining-Pool-c0796bf750984d1e86d68f78287076d4

FYI @BowTiedDeployer to track your dependency on Core Eng Team at Trust Machines.

**Comment by donpdonp** [comment]
https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/821
