### ISSUE TITLE
Write systems design document

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/stacks-sbtc#96]
IMO it would also help to have a higher-level design doc that outlines how the different pieces come together. This can help uncover dependencies early, among other things. This doesn't preclude separate docs for individual components where appropriate (e.g. StackerDB).

Taken from: https://github.com/stacks-network/stacks-blockchain/discussions/3563

**Comment by empeje** [comment]
Sharing tools that might be helpful for this project: Mermaid. It can help us make diagram as code. GitHub supports it natively now :)

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
